version: '3.8'

services:

  mysql:
    container_name: wordwave_mySQL
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
      MYSQL_DATABASE: wordwave_db
    restart: always
    networks:
      - mynet
  redis:
    container_name: wordwave_redis
    image: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - mynet

  backend:
    container_name: backend
    image: ajn044/wordwave
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - mynet


networks:
  mynet:
    driver: bridge
