package com.wordwave.voca;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.annotation.Rollback;

import com.wordwave.voca.data.VocaDataCode;
import com.wordwave.voca.data.VocaDataTool;
import com.wordwave.vocabook.VocaBookRepository;

import jakarta.transaction.Transactional;

//VOCA DATA 생성 테스트
@SpringBootTest
public class VocaDataTest {
	
	//TODO: VOCABOOK DATA부터 넣어야함 !!!
	private static final long VOCABOOK_BASIC_ID = 3; //기초
	private static final long VOCABOOK_TOEIC_ID = 4; //토익
	
	
	@Autowired
	private VocaBookRepository vocaBookRepository;
	@Autowired
	private VocaService vocaService;
	@Autowired
	private VocaDataCode vocaDataCode;
	@Autowired
	private VocaDataTool vocaDataTool;
	@Autowired
	private VocaRepository vocaRepository;
	
	
	@Test
	@Rollback(false)
	@DisplayName("토익 영단어 챕터1 채용파트 영단어 40개 넣기")
	@Disabled
	void testInsertToeicVocaChapter1() { //테스트성공

		String recruiting = "resume|	이력서|	채용\r\n"
				+ "applicant|	지원자 신청자|	채용\r\n"
				+ "requirement|	필요조건 요건|	채용\r\n"
				+ "meet|	(필요요구 등을)만족시키다|	채용\r\n"
				+ "qualified|	자격있는 적격의|	채용\r\n"
				+ "candidate|	후보자 지원자|	채용\r\n"
				+ "confidence|	확신 자신 신임|	채용\r\n"
				+ "highly|	매우 대단히|	채용\r\n"
				+ "professional|	전문적인 직업의 전문가|	채용\r\n"
				+ "interview|	면접 면접을 보다|	채용\r\n"
				+ "hire|	고용하다|	채용\r\n"
				+ "training|	교육 훈련|	채용\r\n"
				+ "reference|	추천서 참고|	채용\r\n"
				+ "position|	일자리 직책 두다|	채용\r\n"
				+ "achievement|	성취 달성|	채용\r\n"
				+ "impressed|	인상 깊게 생각하는 감명을 받은|	채용\r\n"
				+ "excellent|	훌륭한|	채용\r\n"
				+ "eligible|	자격이 있는 적격의|	채용\r\n"
				+ "identify|	알아보다 확인하다|	채용\r\n"
				+ "associate|	관련시키다|	채용\r\n"
				+ "condition|	조건|	채용\r\n"
				+ "employment|	고용|	채용\r\n"
				+ "lack|	~이 없다 부족|	채용\r\n"
				+ "managerial|	관리의|	채용\r\n"
				+ "diligent|	성실한|	채용\r\n"
				+ "familiar|	익숙한 친숙한|	채용\r\n"
				+ "proficiency|	숙달 능숙|	채용\r\n"
				+ "prospective|	장래의 미래의|	채용\r\n"
				+ "appeal|	관심을 끌다 매력적이다|	채용\r\n"
				+ "specialize|	~을 전공하다 전문적으로 다루다|	채용\r\n"
				+ "apprehensive|	걱정하는 염려하는|	채용\r\n"
				+ "consultant|	고문 컨설턴트|	채용\r\n"
				+ "entitle|	자격을 주다|	채용\r\n"
				+ "degree|	학위|	채용\r\n"
				+ "payroll|	임금대장 금료명부|	채용\r\n"
				+ "recruit|	(신입사원등을)모집하다|	채용\r\n"
				+ "certification|	증명서 증명|	채용\r\n"
				+ "occupation|	직업|	채용\r\n"
				+ "wage|	임금 급료|	채용\r\n";
		String[] recruitingArr = recruiting.split("\n");
		for(String sentence : recruitingArr) {
			String[] word = sentence.split("\\|");
			VocaDTO voca = VocaDTO.builder()
							      .korWord(word[1].trim())
							      .engWord(word[0].trim())
							      .category(word[2].trim())
							      .build();
			vocaService.create(voca, VOCABOOK_TOEIC_ID);
			
		}
	}
	
	
	
	@Test
	@Rollback(false)
	@DisplayName("토익 영단어 챕터2 법률파트 영단어 40개 넣기")
	@Disabled
	void testInsertToeicVocaChapter2() { //테스트 성공
		String legislation = "attire|	복장 옷차림새|	법률\r\n"
				+ "code|	규범 관례;암호|	법률\r\n"
				+ "concern|	우려 걱정 문제 일 ~을 걱정스럽게 하다; 영향을 미치다 관련되다.|	법률\r\n"
				+ "policy|	규정; 보험 증권|	법률\r\n"
				+ "comply|	준수하다 따르다|	법률\r\n"
				+ "regulation|	규정|	법률\r\n"
				+ "exception|	예외|	법률\r\n"
				+ "adhere|	지키다 고수하다|	법률\r\n"
				+ "severely|	엄격하게 심하게|	법률\r\n"
				+ "refrain|	자제하다 삼가다|	법률\r\n"
				+ "permission|	허락 허가|	법률\r\n"
				+ "access|	이용권한 접근;통로 ~에 접근하다 도달하다|	법률\r\n"
				+ "thoroughly|	철저하게 완전히 대단히|	법률\r\n"
				+ "revise|	(의견 계획을)수정하다 변경하다|	법률\r\n"
				+ "approach|	접근법 처리방법|	법률\r\n"
				+ "approval|	승인 인가|	법률\r\n"
				+ "form|	종류 유형 양식|	법률\r\n"
				+ "immediately|	즉시 곧|	법률\r\n"
				+ "inspection|	점검 검사|	법률\r\n"
				+ "arrangement|	준비 마련 주선|	법률\r\n"
				+ "procedure|	절차|	법률\r\n"
				+ "negative|	부정적인 비관적인|	법률\r\n"
				+ "mandate|	명령하다 지시하다 권한 지시 명령|	법률\r\n"
				+ "effect|	(법률등의)효력 효과 영향 결과로서 ~을 가져오다|	법률\r\n"
				+ "drastically|	심하게 과감하게 철저하게|	법률\r\n"
				+ "according to|	~에 따라|	법률\r\n"
				+ "enable|	(무엇을)가능하게 하다|	법률\r\n"
				+ "standard|	기준 표준|	법률\r\n"
				+ "constant|	지속적인 끊임없이 계속하는|	법률\r\n"
				+ "act|	법령 결의서; 행위 행동 결정하다 판결을 내리다 행동하다|	법률\r\n"
				+ "compensation|	보상금 보상|	법률\r\n"
				+ "ban|	금지 금지하다|	법률\r\n"
				+ "obligation|	의무 책임|	법률\r\n"
				+ "authorize|	~을 인가하다 권한을 부여하다.|	법률\r\n"
				+ "prohibit|	금지하다|	법률\r\n"
				+ "abolish|	(제도 법률등을)폐지하다|	법률\r\n"
				+ "enforce|	(법률을)시행하다 집행하다|	법률\r\n"
				+ "habit|	습관 버릇|	법률\r\n"
				+ "lagislation|	법률 법규|	법률\r\n"
				+ "restrict|	한정하다 제한하다|	법률\r\n";
		String[] legislationArr = legislation.split("\n");
		for(String sentence : legislationArr) {
			String[] word = sentence.split("\\|");
			VocaDTO voca = VocaDTO.builder()
								  .engWord(word[0].trim())
								  .korWord(word[1].trim())
								  .category(word[2].trim())
								  .build();
			vocaService.create(voca, VOCABOOK_TOEIC_ID);
		}
	}
	
	@Test
	@Rollback(false)
	@DisplayName("basic 단어장 영단어 1800개 할당")
	@Disabled
	void testInsertBasicVoca1800() {
		String legislation = "abandon|	버리다|\r\n"
				+ "able|	할 수 있는|\r\n"
				+ "aboard|	배로|\r\n"
				+ "abroad|	외국으로|\r\n"
				+ "absent|	부재의|\r\n"
				+ "absolute|	절대의|\r\n"
				+ "absorb|	흡수하다|\r\n"
				+ "abstract|	추상적인|\r\n"
				+ "abundant|	풍부한|\r\n"
				+ "abuse|	남용|\r\n"
				+ "accelerate|	가속하다 속도가 가해지다|\r\n"
				+ "accept|	받아들이다|\r\n"
				+ "access|	접근|\r\n"
				+ "accommodate|	수용하다|\r\n"
				+ "accompany|	동반하다|\r\n"
				+ "accomplish|	이루다|\r\n"
				+ "account|	설명하다 계산|\r\n"
				+ "accurate|	정확한|\r\n"
				+ "accuse|	고발하다|\r\n"
				+ "achieve|	성취하다|\r\n"
				+ "acid|	산 신|\r\n"
				+ "acknowledge|	인정하다|\r\n"
				+ "acquire|	얻다|\r\n"
				+ "activate|	활동적으로 하다|\r\n"
				+ "actual|	현실의|\r\n"
				+ "acute|	날카로운|\r\n"
				+ "adapt|	적용시키다|\r\n"
				+ "addict|	열중하게 하다|\r\n"
				+ "adequate|	충분한|\r\n"
				+ "adjust|	맞추다|\r\n"
				+ "administer|	관리하다|\r\n"
				+ "admire|	감복하다|\r\n"
				+ "admission|	입장|\r\n"
				+ "admit|	받아들이다|\r\n"
				+ "adolescent|	청년기의|\r\n"
				+ "adopt|	채용하다|\r\n"
				+ "advance|	나아가다|\r\n"
				+ "advantage|	유리한 입장|\r\n"
				+ "advertize|	광고하다|\r\n"
				+ "advocate|	변호사|\r\n"
				+ "affair|	일|\r\n"
				+ "affect|	영향을 주다|\r\n"
				+ "affection|	애정|\r\n"
				+ "afford|	여유가 있다|\r\n"
				+ "agency|	기능|\r\n"
				+ "agenda|	안건|\r\n"
				+ "agent|	대리인|\r\n"
				+ "aggressive|	침략적인|\r\n"
				+ "agriculture|	농업|\r\n"
				+ "aid|	도와 주다|\r\n"
				+ "aim|	겨누다|\r\n"
				+ "aircraft|	항공기|\r\n"
				+ "aisle|	측면복도|\r\n"
				+ "alert|	빈틈없는|\r\n"
				+ "alien|	외국의|\r\n"
				+ "alike|	비슷한|\r\n"
				+ "alive|	살아있는|\r\n"
				+ "allow|	허락하다|\r\n"
				+ "ally|	동맹하다|\r\n"
				+ "alongside|	-의 곁에|\r\n"
				+ "alter|	바꾸다|\r\n"
				+ "alternative|	어느 한쪽의 양자택일|\r\n"
				+ "although|	비록 -일지라도|\r\n"
				+ "altogether|	전혀|\r\n"
				+ "amaze|	깜짝 놀라게 하다|\r\n"
				+ "ambassador|	대사|\r\n"
				+ "ambition|	야심|\r\n"
				+ "among|	-중에|\r\n"
				+ "amount|	(금액이)-이 되다|\r\n"
				+ "amuse|	재미나게 하다|\r\n"
				+ "analyze|	분해하다|\r\n"
				+ "anchor|	닻|\r\n"
				+ "ancient|	옛날의|\r\n"
				+ "angle|	각|\r\n"
				+ "anniversary|	기념일 예년의|\r\n"
				+ "announce|	알리다|\r\n"
				+ "annoy|	귀찮게하다|\r\n"
				+ "annual|	일년의|\r\n"
				+ "anticipate|	예기하다|\r\n"
				+ "anxiety|	근심|\r\n"
				+ "anxious|	걱정되는|\r\n"
				+ "apart|	떨어져서|\r\n"
				+ "apology|	사과|\r\n"
				+ "apparent|	명백한|\r\n"
				+ "appeal|	간청하다|\r\n"
				+ "appear|	나타나다|\r\n"
				+ "applicant|	지원자|\r\n"
				+ "apply|	(물건을)대다|\r\n"
				+ "appoint|	지정하다|\r\n"
				+ "appreciate|	감상하다|\r\n"
				+ "approach|	다가가다|\r\n"
				+ "appropriate|	적당한|\r\n"
				+ "approve|	시인하다|\r\n"
				+ "approximate|	어림셈의|\r\n"
				+ "architect|	건축가|\r\n"
				+ "architecture|	건축|\r\n"
				+ "argue|	논하다|\r\n"
				+ "arise|	생기다|\r\n"
				+ "army|	육군|\r\n"
				+ "arrange|	가지런히 하다|\r\n"
				+ "arrest|	체포하다|\r\n"
				+ "arrow|	화살|\r\n"
				+ "article|	물품|\r\n"
				+ "artificial|	인공의|\r\n"
				+ "ash|	회|\r\n"
				+ "aside|	곁에|\r\n"
				+ "asleep|	잠들은|\r\n"
				+ "aspect|	관점|\r\n"
				+ "aspire|	열망하다|\r\n"
				+ "assemble|	모으다|\r\n"
				+ "assert|	단언하다|\r\n"
				+ "assess|	(세금 등을)사정하다|\r\n"
				+ "asset|	자산|\r\n"
				+ "assign|	할당하다|\r\n"
				+ "assist|	돕다|\r\n"
				+ "associate|	연상하다|\r\n"
				+ "assume|	취하다|\r\n"
				+ "assure|	보증하다|\r\n"
				+ "astonish|	놀라게 하다|\r\n"
				+ "athlete|	운동가|\r\n"
				+ "atmosphere|	대기|\r\n"
				+ "atom|	원자|\r\n"
				+ "attach|	붙이다|\r\n"
				+ "attack|	공격하다|\r\n"
				+ "attain|	이르다|\r\n"
				+ "attempt|	시도하다|\r\n"
				+ "attend|	출석하다|\r\n"
				+ "attention|	주의|\r\n"
				+ "attitude|	태도|\r\n"
				+ "attract|	끌어 당기다|\r\n"
				+ "attribute|	속성|\r\n"
				+ "auction|	경매|\r\n"
				+ "audience|	청중|\r\n"
				+ "author|	저자|\r\n"
				+ "autobiography|	자서전|\r\n"
				+ "automatic|	자동의|\r\n"
				+ "automobile|	자동차 자동차의|\r\n"
				+ "available|	쓸모있는|\r\n"
				+ "avenue|	가로수길|\r\n"
				+ "average|	평균|\r\n"
				+ "avoid|	피하다|\r\n"
				+ "await|	기다리다|\r\n"
				+ "awake|	깨우다|\r\n"
				+ "award|	상|\r\n"
				+ "aware|	알고 있는|\r\n"
				+ "awesome|	무서운|\r\n"
				+ "awful|	두려운|\r\n"
				+ "awkward|	어색한|\r\n"
				+ "balance|	균형|\r\n"
				+ "ban|	금지|\r\n"
				+ "bang|	강타|\r\n"
				+ "bar|	막대기|\r\n"
				+ "bare|	벌거벗은|\r\n"
				+ "bargain|	매매|\r\n"
				+ "bark|	짖다|\r\n"
				+ "barn|	헛간|\r\n"
				+ "barrier|	장벽|\r\n"
				+ "basis|	기초|\r\n"
				+ "bay|	만|\r\n"
				+ "beam|	광선|\r\n"
				+ "beard|	턱수염|\r\n"
				+ "beast|	짐승|\r\n"
				+ "beat|	치다|\r\n"
				+ "beer|	맥주|\r\n"
				+ "beg|	청하다|\r\n"
				+ "behalf|	위함|\r\n"
				+ "behave|	행동하다|\r\n"
				+ "behavior|	행동|\r\n"
				+ "belong|	속하다|\r\n"
				+ "bend|	구부리다|\r\n"
				+ "beneath|	-의 바로 아래에|\r\n"
				+ "benefit|	이익|\r\n"
				+ "berry|	액과|\r\n"
				+ "bet|	걸다|\r\n"
				+ "betray|	배반하다|\r\n"
				+ "beyond|	저편에|\r\n"
				+ "bias|	치우침|\r\n"
				+ "bible|	성서, 성경|\r\n"
				+ "billion|	10억|\r\n"
				+ "bin|	궤|\r\n"
				+ "bind|	매다|\r\n"
				+ "biography|	전기|\r\n"
				+ "biology|	생물학|\r\n"
				+ "bit|	bite의 과거(분사) 작은 조각|\r\n"
				+ "bitter|	쓴|\r\n"
				+ "blame|	책망하다|\r\n"
				+ "blank|	공백|\r\n"
				+ "blanket|	담요|\r\n"
				+ "blend|	혼합하다|\r\n"
				+ "bless|	축복하다|\r\n"
				+ "blind|	눈먼|\r\n"
				+ "blink|	(눈을)깜빡거리다|\r\n"
				+ "blonde|	(살결이 흰)금발의 여성|\r\n"
				+ "bloom|	쇳덩이|\r\n"
				+ "blossom|	(과수의)꽃|\r\n"
				+ "blow|	강타|\r\n"
				+ "boil|	끓다|\r\n"
				+ "bold|	대담한|\r\n"
				+ "bond|	결속|\r\n"
				+ "boom|	굉음|\r\n"
				+ "boost|	뒤를 밀기|\r\n"
				+ "border|	가장자리|\r\n"
				+ "bore|	고조|\r\n"
				+ "bother|	괴롭히다 근심하다 귀찮음|\r\n"
				+ "bounce|	뛰어오르다|\r\n"
				+ "boundary|	경계|\r\n"
				+ "bow|	절|\r\n"
				+ "breast|	가슴|\r\n"
				+ "breathe|	숨쉬다|\r\n"
				+ "breeze|	미풍|\r\n"
				+ "brick|	벽돌|\r\n"
				+ "bride|	신부|\r\n"
				+ "brief|	단시간의|\r\n"
				+ "brilliant|	빛나는|\r\n"
				+ "broad|	(폭이)넓은|\r\n"
				+ "broadcast|	방송하다|\r\n"
				+ "budget|	예산|\r\n"
				+ "bull|	황소|\r\n"
				+ "bullet|	탄환|\r\n"
				+ "bully|	약한 자를 못살게 구는 자|\r\n"
				+ "bump|	충돌 부딪치다|\r\n"
				+ "bunch|	송이|\r\n"
				+ "bundle|	다발|\r\n"
				+ "burden|	후렴|\r\n"
				+ "burst|	파열하다|\r\n"
				+ "bury|	묻다|\r\n"
				+ "bush|	덤불|\r\n"
				+ "butcher|	정육점주인|\r\n"
				+ "buzz|	윙윙거리는 소리|\r\n"
				+ "cab|	택시|\r\n"
				+ "cabin|	선실|\r\n"
				+ "cable|	해저전신|\r\n"
				+ "calculate|	계산하다|\r\n"
				+ "cancel|	취소하다|\r\n"
				+ "cancer|	암|\r\n"
				+ "candidate|	지원자|\r\n"
				+ "canvas|	돛베|\r\n"
				+ "capable|	할 수 있는|\r\n"
				+ "cape|	곶|\r\n"
				+ "capital|	수위의|\r\n"
				+ "capture|	붙잡다(=catch)|\r\n"
				+ "career|	경력|\r\n"
				+ "carve|	조각하다|\r\n"
				+ "cast|	던지다|\r\n"
				+ "casual|	우연한|\r\n"
				+ "category|	범주|\r\n"
				+ "cattle|	소|\r\n"
				+ "causal|	원인의|\r\n"
				+ "cause|	원인|\r\n"
				+ "caution|	조심|\r\n"
				+ "cave|	동굴 굴을 파다 꺼지다|\r\n"
				+ "cease|	그만두다 그치다 중지|\r\n"
				+ "ceiling|	천장|\r\n"
				+ "celebrate|	경축하다|\r\n"
				+ "celebrity|	명성|\r\n"
				+ "cell|	작은 방|\r\n"
				+ "censor|	검열관|\r\n"
				+ "century|	1세기|\r\n"
				+ "certificate|	증명서|\r\n"
				+ "chairman|	의장|\r\n"
				+ "challenge|	도전|\r\n"
				+ "chaos|	혼돈|\r\n"
				+ "character|	인격|\r\n"
				+ "characteristic|	특유한|\r\n"
				+ "charge|	요금|\r\n"
				+ "charity|	자비|\r\n"
				+ "charm|	매력|\r\n"
				+ "chase|	쫓다|\r\n"
				+ "chat|	잡담|\r\n"
				+ "cheek|	볼|\r\n"
				+ "cheer|	갈채|\r\n"
				+ "chef|	쿡|\r\n"
				+ "chemical|	화학의|\r\n"
				+ "chemistry|	화학|\r\n"
				+ "chest|	가슴팍|\r\n"
				+ "chew|	씹다|\r\n"
				+ "chief|	우두머리|\r\n"
				+ "chill|	차가움|\r\n"
				+ "chin|	턱(끝) 턱에 대다|\r\n"
				+ "chip|	(나무)토막|\r\n"
				+ "choir|	(교회의)성가대|\r\n"
				+ "chop|	(도끼 등으로)자르다|\r\n"
				+ "chorus|	합창|\r\n"
				+ "cigarette|	궐련|\r\n"
				+ "circulate|	순환하다|\r\n"
				+ "circumstance|	환경|\r\n"
				+ "cite|	인용하다(quote)|\r\n"
				+ "citizen|	시민|\r\n"
				+ "civil|	시민의|\r\n"
				+ "claim|	요구하다|\r\n"
				+ "clap|	짝짝|\r\n"
				+ "clarify|	맑게 하다|\r\n"
				+ "clash|	충돌하다|\r\n"
				+ "classic|	고전의|\r\n"
				+ "classify|	분류하다|\r\n"
				+ "clause|	조항|\r\n"
				+ "clay|	찰흙|\r\n"
				+ "client|	소송의뢰인|\r\n"
				+ "cliff|	절벽|\r\n"
				+ "climate|	기후|\r\n"
				+ "cling|	밀착하다|\r\n"
				+ "clinic|	병원|\r\n"
				+ "clue|	단서|\r\n"
				+ "cluster|	떼|\r\n"
				+ "coach|	역마차|\r\n"
				+ "coal|	석탄|\r\n"
				+ "coast|	연안|\r\n"
				+ "code|	법전|\r\n"
				+ "coincide|	일치하다|\r\n"
				+ "collaborate|	공동으로 일하다|\r\n"
				+ "collapse|	붕괴|\r\n"
				+ "collar|	칼라|\r\n"
				+ "colleague|	동료|\r\n"
				+ "colony|	식민지|\r\n"
				+ "column|	(신문 등의)난|\r\n"
				+ "combat|	격투하다|\r\n"
				+ "combine|	결합하다|\r\n"
				+ "comfort|	위안|\r\n"
				+ "command|	명령하다|\r\n"
				+ "comment|	논평|\r\n"
				+ "commerce|	상업|\r\n"
				+ "commission|	위임|\r\n"
				+ "commit|	위탁하다|\r\n"
				+ "committee|	위원회|\r\n"
				+ "communicate|	알리다|\r\n"
				+ "communist|	공산주의자|\r\n"
				+ "community|	공동생활체|\r\n"
				+ "companion|	동료|\r\n"
				+ "compare|	비교하다|\r\n"
				+ "compete|	경쟁하다|\r\n"
				+ "competent|	능력있는|\r\n"
				+ "complain|	불평하다|\r\n"
				+ "complement|	보완하는 것|\r\n"
				+ "complete|	완성하다|\r\n"
				+ "complex|	합성물|\r\n"
				+ "complicate|	복잡하게 하다|\r\n"
				+ "compose|	구성하다|\r\n"
				+ "comprehensive|	이해력있는|\r\n"
				+ "conceal|	숨기다|\r\n"
				+ "concentrate|	집중하다|\r\n"
				+ "concept|	개념|\r\n"
				+ "concern|	관계하다|\r\n"
				+ "conclude|	결정하다|\r\n"
				+ "concrete|	구체적인 응고물|\r\n"
				+ "conduct|	행위 이끌다|\r\n"
				+ "confess|	실토하다|\r\n"
				+ "confident|	확신하는|\r\n"
				+ "confine|	국경|\r\n"
				+ "confirm|	확인하다|\r\n"
				+ "conflict|	투쟁|\r\n"
				+ "conform|	일치시키다|\r\n"
				+ "confront|	직면하다|\r\n"
				+ "confuse|	혼란시키다|\r\n"
				+ "congress|	회의|\r\n"
				+ "connect|	잇다 이어지다|\r\n"
				+ "conscience|	양심|\r\n"
				+ "conscious|	의식적인|\r\n"
				+ "consider|	숙고하다|\r\n"
				+ "consist|	-으로 이루어지다|\r\n"
				+ "consistent|	시종일관한|\r\n"
				+ "constant|	불변의|\r\n"
				+ "construct|	건조하다|\r\n"
				+ "consult|	상의하다|\r\n"
				+ "consume|	소비하다|\r\n"
				+ "contact|	접촉|\r\n"
				+ "contain|	내포하다|\r\n"
				+ "content|	만족하여|\r\n"
				+ "context|	문맥|\r\n"
				+ "continent|	자제심이 있는|\r\n"
				+ "continue|	계속하다|\r\n"
				+ "contract|	계약|\r\n"
				+ "contrary|	반대의 반대 거꾸로|\r\n"
				+ "contrast|	대조|\r\n"
				+ "contribute|	기부하다|\r\n"
				+ "controversy|	논쟁|\r\n"
				+ "convenient|	편리한|\r\n"
				+ "conversation|	회화|\r\n"
				+ "convey|	나르다|\r\n"
				+ "convict|	유죄로 판결하다 죄수|\r\n"
				+ "convince|	확신시키다|\r\n"
				+ "cooperate|	협동하다|\r\n"
				+ "cop|	순경|\r\n"
				+ "cope|	코우프(성직자의 긴 겉옷)|\r\n"
				+ "copyright|	판권|\r\n"
				+ "cord|	밧줄|\r\n"
				+ "core|	핵심|\r\n"
				+ "corn|	티눈|\r\n"
				+ "corporate|	법인조직의|\r\n"
				+ "correct|	옳은|\r\n"
				+ "correspond|	일치하다|\r\n"
				+ "corrupt|	타락한|\r\n"
				+ "costume|	복장|\r\n"
				+ "cottage|	시골집|\r\n"
				+ "couch|	침대|\r\n"
				+ "cough|	기침 기침을 하다 기침을 하여 -을 뱉어내다|\r\n"
				+ "council|	회의|\r\n"
				+ "counsel|	의논|\r\n"
				+ "count|	계산|\r\n"
				+ "counter|	계산하는 사람|\r\n"
				+ "courage|	용기|\r\n"
				+ "cowboy|	목동|\r\n"
				+ "crack|	찰싹 소리내다 금가다 날카로운소리|\r\n"
				+ "craft|	솜씨|\r\n"
				+ "crash|	도산|\r\n"
				+ "crawl|	네발로 기다|\r\n"
				+ "create|	창조하다|\r\n"
				+ "creature|	창조물|\r\n"
				+ "credible|	믿을 수 있는|\r\n"
				+ "credit|	신용|\r\n"
				+ "crew|	승무원|\r\n"
				+ "cricket|	크리켓|\r\n"
				+ "crime|	범죄|\r\n"
				+ "criminal|	죄의|\r\n"
				+ "crisis|	위기|\r\n"
				+ "crisp|	파삭파삭한|\r\n"
				+ "critic|	비평가|\r\n"
				+ "criticize|	비평하다|\r\n"
				+ "criticism|	비평|\r\n"
				+ "crop|	수확|\r\n"
				+ "crucial|	결정적인|\r\n"
				+ "cruel|	잔인한|\r\n"
				+ "cruise|	순항하다|\r\n"
				+ "crush|	눌러 부수다|\r\n"
				+ "crystal|	수정|\r\n"
				+ "cultivate|	경작하다|\r\n"
				+ "cupboard|	찬장|\r\n"
				+ "cure|	치료|\r\n"
				+ "curl|	곱슬머리 머리털을 지지다|\r\n"
				+ "current|	유행의|\r\n"
				+ "curry|	카레요리 카레로 맛을 내다|\r\n"
				+ "curve|	곡선|\r\n"
				+ "custom|	습관|\r\n"
				+ "dairy|	낙농장|\r\n"
				+ "dam|	댐|\r\n"
				+ "damage|	손해|\r\n"
				+ "damp|	축축한 습기 적시다|\r\n"
				+ "dare|	au감히 -하다|\r\n"
				+ "darling|	귀여운|\r\n"
				+ "dash|	돌진|\r\n"
				+ "database|	데이터베이스|\r\n"
				+ "dawn|	새벽 날이 새다|\r\n"
				+ "deal|	양|\r\n"
				+ "debate|	토론 토론하다|\r\n"
				+ "debt|	빚|\r\n"
				+ "decade|	10년간|\r\n"
				+ "decay|	쇠퇴하다|\r\n"
				+ "decision|	결정|\r\n"
				+ "deck|	갑판|\r\n"
				+ "declare|	선언하다|\r\n"
				+ "decline|	기울다|\r\n"
				+ "decorate|	장식하다|\r\n"
				+ "decrease|	감소하다|\r\n"
				+ "defeat|	패배|\r\n"
				+ "defense|	방어|\r\n"
				+ "defend|	방어하다|\r\n"
				+ "defendant|	피고 피고의|\r\n"
				+ "define|	정의하다|\r\n"
				+ "definite|	일정한|\r\n"
				+ "degree|	도|\r\n"
				+ "delay|	늦추다|\r\n"
				+ "delete|	삭제하다|\r\n"
				+ "delicate|	미묘한|\r\n"
				+ "delight|	즐겁게하다 즐거워하다|\r\n"
				+ "deliver|	인도하다|\r\n"
				+ "demand|	요구하다|\r\n"
				+ "democracy|	민주주의|\r\n"
				+ "democrat|	민주주의자|\r\n"
				+ "demon|	악마|\r\n"
				+ "demonstrate|	증명하다|\r\n"
				+ "dense|	짙은|\r\n"
				+ "deny|	부정하다|\r\n"
				+ "department|	부|\r\n"
				+ "departure|	출발|\r\n"
				+ "depend|	좌우되다|\r\n"
				+ "dependence|	종속|\r\n"
				+ "depress|	억압하다|\r\n"
				+ "derive|	이끌어 내다|\r\n"
				+ "descend|	내려오다|\r\n"
				+ "describe|	기술하다|\r\n"
				+ "description|	서술|\r\n"
				+ "desert|	버리다|\r\n"
				+ "deserve|	 -할 만하다|\r\n"
				+ "desire|	바라다|\r\n"
				+ "despair|	절망하다|\r\n"
				+ "desperate|	절망적인|\r\n"
				+ "despite|	-에도 불구하고 모욕|\r\n"
				+ "destination|	목적지|\r\n"
				+ "destiny|	운명|\r\n"
				+ "destroy|	파괴하다|\r\n"
				+ "destruction|	파괴|\r\n"
				+ "detach|	분리하다|\r\n"
				+ "detail|	상설|\r\n"
				+ "detect|	간파하다|\r\n"
				+ "determine|	결정하다|\r\n"
				+ "develop|	발달하다|\r\n"
				+ "device|	고안|\r\n"
				+ "devil|	악마|\r\n"
				+ "devise|	고안하다|\r\n"
				+ "devote|	바치다|\r\n"
				+ "dictionary|	사전|\r\n"
				+ "dig|	파다|\r\n"
				+ "diminish|	감소하다|\r\n"
				+ "dip|	담그다|\r\n"
				+ "diplomat|	외교관|\r\n"
				+ "direct|	지도하다|\r\n"
				+ "disabled|	불구가 된|\r\n"
				+ "disadvantage|	불리|\r\n"
				+ "disagree|	일치하지 않다|\r\n"
				+ "disappear|	안보이게 되다|\r\n"
				+ "disappoint|	실망시키다|\r\n"
				+ "disaster|	천재|\r\n"
				+ "discipline|	훈련|\r\n"
				+ "disclose|	나타내다|\r\n"
				+ "discount|	할인|\r\n"
				+ "discover|	발견하다|\r\n"
				+ "disease|	병|\r\n"
				+ "disgust|	불쾌하게 하다|\r\n"
				+ "dismiss|	떠나게 하다|\r\n"
				+ "disorder|	난잡|\r\n"
				+ "display|	보이다|\r\n"
				+ "dispose|	배열하다|\r\n"
				+ "distant|	떨어진|\r\n"
				+ "distract|	전환시키다|\r\n"
				+ "distribute|	분배하다|\r\n"
				+ "district|	지구|\r\n"
				+ "disturb|	교란하다|\r\n"
				+ "dive|	뛰어들다|\r\n"
				+ "diverse|	다양한|\r\n"
				+ "divorce|	이혼|\r\n"
				+ "document|	서류|\r\n"
				+ "domain|	영토|\r\n"
				+ "domestic|	가정의|\r\n"
				+ "donate|	증여하다|\r\n"
				+ "dot|	점|\r\n"
				+ "doubt|	의심|\r\n"
				+ "dozen|	1다스|\r\n"
				+ "drag|	끌다|\r\n"
				+ "drawer|	제도사|\r\n"
				+ "drown|	물에빠뜨리다|\r\n"
				+ "drug|	약제|\r\n"
				+ "due|	지급기일이 된|\r\n"
				+ "dull|	둔한|\r\n"
				+ "dump|	내버리다|\r\n"
				+ "dust|	먼지|\r\n"
				+ "duty|	의무|\r\n"
				+ "dwell|	거주하다|\r\n"
				+ "dynamic|	동적인|\r\n"
				+ "each|	각각의|\r\n"
				+ "eager|	열심인|\r\n"
				+ "earn|	일하여 벌다|\r\n"
				+ "ease|	안락|\r\n"
				+ "economy|	절약|\r\n"
				+ "edge|	끝머리|\r\n"
				+ "edit|	편집하다|\r\n"
				+ "educate|	교육하다|\r\n"
				+ "effect|	결과|\r\n"
				+ "effective|	효과적인|\r\n"
				+ "efficient|	능률적인|\r\n"
				+ "effort|	노력|\r\n"
				+ "either|	어느 하나의|\r\n"
				+ "elect|	선거하다|\r\n"
				+ "electric|	전기의|\r\n"
				+ "electronic|	전자(학)의|\r\n"
				+ "elegant|	우아한|\r\n"
				+ "element|	요소|\r\n"
				+ "eliminate|	제거하다|\r\n"
				+ "else|	그 밖에|\r\n"
				+ "embarrass|	난처하게 하다|\r\n"
				+ "embassy|	대사관|\r\n"
				+ "emerge|	나오다|\r\n"
				+ "emergency|	비상사태|\r\n"
				+ "emotion|	감정|\r\n"
				+ "emphasis|	강조|\r\n"
				+ "empire|	제국|\r\n"
				+ "employ|	고용하다|\r\n"
				+ "empty|	빈|\r\n"
				+ "enclose|	에워싸다|\r\n"
				+ "encounter|	조우|\r\n"
				+ "encourage|	용기를 돋우다|\r\n"
				+ "endure|	견디다|\r\n"
				+ "enemy|	적|\r\n"
				+ "engage|	약속하다|\r\n"
				+ "enhance|	향상하다|\r\n"
				+ "enormous|	거대한|\r\n"
				+ "ensure|	-을 책임지다|\r\n"
				+ "enterprise|	기획|\r\n"
				+ "entertain|	즐겁게 하다|\r\n"
				+ "enthusiastic|	열심인|\r\n"
				+ "entire|	전체의|\r\n"
				+ "entry|	들어감|\r\n"
				+ "envelope|	봉투|\r\n"
				+ "environment|	환경|\r\n"
				+ "envy|	질투|\r\n"
				+ "episode|	삽화|\r\n"
				+ "equal|	같은|\r\n"
				+ "equipment|	장비|\r\n"
				+ "era|	시대|\r\n"
				+ "escape|	도망하다|\r\n"
				+ "escort|	호위하다|\r\n"
				+ "especially|	특히|\r\n"
				+ "essential|	본질적인|\r\n"
				+ "establish|	확립하다|\r\n"
				+ "estimate|	어림잡다|\r\n"
				+ "etc|	등등|\r\n"
				+ "evaluate|	평가하다|\r\n"
				+ "eve|	저녁, 밤|\r\n"
				+ "even|	-조차|\r\n"
				+ "eventually|	결국|\r\n"
				+ "ever|	이전에|\r\n"
				+ "evident|	명백한|\r\n"
				+ "evil|	사악한|\r\n"
				+ "evolution|	진화|\r\n"
				+ "evolve|	진화하다|\r\n"
				+ "exact|	정확한|\r\n"
				+ "exaggerate|	과장하다|\r\n"
				+ "examine|	시험하다|\r\n"
				+ "exceed|	넘다|\r\n"
				+ "excellent|	우수한|\r\n"
				+ "except|	-을 제외하고는 제외하다|\r\n"
				+ "excess|	초과|\r\n"
				+ "exchange|	교환하다|\r\n"
				+ "excite|	흥분시키다|\r\n"
				+ "exclude|	배척하다|\r\n"
				+ "excuse|	변명|\r\n"
				+ "exhaust|	다 써버리다|\r\n"
				+ "exhibit|	보이다|\r\n"
				+ "exist|	존재하다|\r\n"
				+ "exotic|	외국의|\r\n"
				+ "expand|	펴다|\r\n"
				+ "expect|	기대하다|\r\n"
				+ "expense|	지출|\r\n"
				+ "expensive|	비용이 드는|\r\n"
				+ "experience|	경험|\r\n"
				+ "experiment|	실험|\r\n"
				+ "expert|	숙련가|\r\n"
				+ "explain|	설명하다|\r\n"
				+ "explode|	폭발시키다|\r\n"
				+ "explore|	탐험하다|\r\n"
				+ "export|	수출하다 수출|\r\n"
				+ "expose|	쐬다, 드러내다, 맞히다|\r\n"
				+ "express|	발표하다|\r\n"
				+ "extend|	뻗다|\r\n"
				+ "extent|	넓이|\r\n"
				+ "external|	외부의|\r\n"
				+ "extinct|	꺼진|\r\n"
				+ "extra|	가외의|\r\n"
				+ "extreme|	극단의|\r\n"
				+ "eyebrow|	눈썹|\r\n"
				+ "fabric|	천|\r\n"
				+ "facility|	쉬움|\r\n"
				+ "factor|	요소|\r\n"
				+ "fade|	바래다|\r\n"
				+ "faint|	기절하다|\r\n"
				+ "fair|	공평한|\r\n"
				+ "faith|	신용|\r\n"
				+ "false|	거짓|\r\n"
				+ "fame|	명성|\r\n"
				+ "familiar|	친한|\r\n"
				+ "fancy|	공상|\r\n"
				+ "fare|	요금|\r\n"
				+ "fascinate|	황홀케 하다|\r\n"
				+ "fasten|	단단히 고정시키다|\r\n"
				+ "fate|	숙명|\r\n"
				+ "fault|	결점|\r\n"
				+ "favor|	호의|\r\n"
				+ "fear|	두려움|\r\n"
				+ "feature|	얼굴의 생김새|\r\n"
				+ "fee|	요금|\r\n"
				+ "feed|	음식(먹이)을 주다|\r\n"
				+ "fellow|	동무|\r\n"
				+ "female|	여성|\r\n"
				+ "ferry|	나루터|\r\n"
				+ "few|	소수의|\r\n"
				+ "fiber|	섬유|\r\n"
				+ "fierce|	흉포한|\r\n"
				+ "figure|	모습|\r\n"
				+ "filter|	여과기 여과하다|\r\n"
				+ "final|	최후의|\r\n"
				+ "finance|	재정|\r\n"
				+ "finite|	한정되어 있는|\r\n"
				+ "firm|	굳은|\r\n"
				+ "fist|	주먹|\r\n"
				+ "fit|	맞는|\r\n"
				+ "flame|	불꽃|\r\n"
				+ "flash|	번쩍임|\r\n"
				+ "flat|	편평한|\r\n"
				+ "flavor|	(독특한)맛|\r\n"
				+ "flaw|	금|\r\n"
				+ "flesh|	살|\r\n"
				+ "flexible|	구부리기 쉬운|\r\n"
				+ "flight|	날기|\r\n"
				+ "float|	뜨다|\r\n"
				+ "flock|	무리|\r\n"
				+ "flood|	홍수|\r\n"
				+ "flourish|	번창하다|\r\n"
				+ "flow|	흐르다|\r\n"
				+ "fold|	주름|\r\n"
				+ "folk|	사람들|\r\n"
				+ "follow|	쫓다|\r\n"
				+ "forbid|	금하다|\r\n"
				+ "force|	힘|\r\n"
				+ "forecast|	예상|\r\n"
				+ "forehead|	이마|\r\n"
				+ "foreign|	외국의|\r\n"
				+ "forgive|	용서하다|\r\n"
				+ "formal|	형식상의|\r\n"
				+ "format|	(서적의)체제|\r\n"
				+ "formation|	형성|\r\n"
				+ "former|	이전의|\r\n"
				+ "forth|	앞으로|\r\n"
				+ "fortunate|	운좋은|\r\n"
				+ "fortune|	운|\r\n"
				+ "forum|	공개토론회|\r\n"
				+ "forward|	앞쪽에|\r\n"
				+ "foundation|	기초|\r\n"
				+ "fountain|	샘|\r\n"
				+ "frame|	구조|\r\n"
				+ "framework|	뼈대|\r\n"
				+ "frankly|	솔직히|\r\n"
				+ "freeze|	얼다|\r\n"
				+ "frequent|	빈번한|\r\n"
				+ "fright|	(갑자기 엄습하는)공포|\r\n"
				+ "frown|	눈살을 찌푸리다|\r\n"
				+ "frustrate|	(계획 등을)좌절시키다|\r\n"
				+ "fuel|	연료|\r\n"
				+ "fulfil|	이행하다|\r\n"
				+ "function|	기능|\r\n"
				+ "fund|	기금|\r\n"
				+ "fundamental|	기초(기준)의|\r\n"
				+ "funeral|	장사|\r\n"
				+ "fur|	모피|\r\n"
				+ "furniture|	가구|\r\n"
				+ "furthermore|	더우기|\r\n"
				+ "gain|	얻다|\r\n"
				+ "gamble|	도박하다 도박 도박해서 잃다|\r\n"
				+ "gang|	한 떼|\r\n"
				+ "gap|	갈라진 틈|\r\n"
				+ "garage|	차고|\r\n"
				+ "gather|	그러모으다|\r\n"
				+ "gear|	톱니바퀴|\r\n"
				+ "gender|	성|\r\n"
				+ "gene|	유전(인)자|\r\n"
				+ "general|	일반적인|\r\n"
				+ "generation|	일대|\r\n"
				+ "generous|	광대한|\r\n"
				+ "genius|	천재|\r\n"
				+ "genre|	유형|\r\n"
				+ "gentle|	온화한|\r\n"
				+ "genuine|	진짜의|\r\n"
				+ "geography|	지리|\r\n"
				+ "geology|	지질학|\r\n"
				+ "glance|	흘긋 봄|\r\n"
				+ "global|	공모양의|\r\n"
				+ "glory|	영광|\r\n"
				+ "glow|	타다|\r\n"
				+ "goat|	염소|\r\n"
				+ "goods|	상품|\r\n"
				+ "gorgeous|	호화로운|\r\n"
				+ "govern|	다스리다|\r\n"
				+ "grab|	붙잡다(=snatch)|\r\n"
				+ "grace|	은총|\r\n"
				+ "grade|	등급|\r\n"
				+ "gradual|	점차적인|\r\n"
				+ "graduate|	학위를 수여하다|\r\n"
				+ "grain|	곡물|\r\n"
				+ "grand|	위대한|\r\n"
				+ "grant|	받아들이다|\r\n"
				+ "graphic|	그려 놓은 듯한|\r\n"
				+ "grateful|	고맙게 생각하는|\r\n"
				+ "grave|	무덤|\r\n"
				+ "greed|	탐욕|\r\n"
				+ "greet|	인사하다|\r\n"
				+ "grief|	심한 슬픔(deep sorrow)|\r\n"
				+ "grip|	잡기|\r\n"
				+ "grocery|	식품잡화류|\r\n"
				+ "guarantee|	보증하다|\r\n"
				+ "guest|	손님|\r\n"
				+ "guideline|	지침|\r\n"
				+ "guilty|	죄지은|\r\n"
				+ "gun|	총|\r\n"
				+ "gymnasium|	실내체조장|\r\n"
				+ "half|	반|\r\n"
				+ "hall|	회관|\r\n"
				+ "hammer|	망치|\r\n"
				+ "handicap|	불리한 조건|\r\n"
				+ "handle|	손잡이|\r\n"
				+ "happen|	(사건 등이)일어나다|\r\n"
				+ "harbor|	항구|\r\n"
				+ "hardly|	거의 -아니다|\r\n"
				+ "harm|	해|\r\n"
				+ "harsh|	거친|\r\n"
				+ "harvest|	수확|\r\n"
				+ "haste|	급함|\r\n"
				+ "hazard|	위험|\r\n"
				+ "heal|	고치다|\r\n"
				+ "health|	건강|\r\n"
				+ "hear|	듣다|\r\n"
				+ "heel|	발뒤꿈치|\r\n"
				+ "height|	높이|\r\n"
				+ "hell|	지옥|\r\n"
				+ "hesitate|	주저하다|\r\n"
				+ "hide|	감추다|\r\n"
				+ "highway|	대도|\r\n"
				+ "hip|	엉덩이|\r\n"
				+ "hire|	고용하다|\r\n"
				+ "hole|	구멍|\r\n"
				+ "holy|	신성한|\r\n"
				+ "honor|	명예|\r\n"
				+ "horizon|	지평선|\r\n"
				+ "horror|	공포|\r\n"
				+ "host|	주인, 집주인 노릇, 호스트|\r\n"
				+ "household|	가족|\r\n"
				+ "hug|	꼭 껴안다|\r\n"
				+ "huge|	거대한|\r\n"
				+ "hurt|	상처내다|\r\n"
				+ "hut|	오두막|\r\n"
				+ "ideal|	이상|\r\n"
				+ "identical|	아주 동일한|\r\n"
				+ "identify|	동일시하다|\r\n"
				+ "ignore|	무시하다|\r\n"
				+ "ill|	병든|\r\n"
				+ "illustrate|	설명하다|\r\n"
				+ "imagine|	상상하다|\r\n"
				+ "imitate|	흉내내다|\r\n"
				+ "immediate|	직접의|\r\n"
				+ "immune|	면역성의|\r\n"
				+ "impact|	충격|\r\n"
				+ "imperial|	제국의|\r\n"
				+ "import|	수입하다|\r\n"
				+ "impress|	인상지우다|\r\n"
				+ "improve|	개선하다|\r\n"
				+ "incentive|	자극적인|\r\n"
				+ "incident|	사건|\r\n"
				+ "include|	포함하다|\r\n"
				+ "income|	수입|\r\n"
				+ "increase|	늘다|\r\n"
				+ "incredible|	믿을 수 없는|\r\n"
				+ "indeed|	참으로|\r\n"
				+ "independent|	독립한|\r\n"
				+ "indicate|	지적하다|\r\n"
				+ "individual|	개인|\r\n"
				+ "industry|	공업|\r\n"
				+ "infant|	유아|\r\n"
				+ "influence|	영향력|\r\n"
				+ "inform|	알리다|\r\n"
				+ "informal|	비공식의|\r\n"
				+ "ingredient|	성분|\r\n"
				+ "inhabit|	살다|\r\n"
				+ "initial|	처음의|\r\n"
				+ "initiate|	시작하다|\r\n"
				+ "inject|	주사하다|\r\n"
				+ "injure|	해치다|\r\n"
				+ "inn|	여인숙|\r\n"
				+ "innocent|	무구한|\r\n"
				+ "innovate|	새롭게 하다|\r\n"
				+ "input|	투입|\r\n"
				+ "insect|	곤충|\r\n"
				+ "insert|	끼워넣다|\r\n"
				+ "insight|	통찰(력)|\r\n"
				+ "insist|	주장하다|\r\n"
				+ "inspect|	검사하다|\r\n"
				+ "inspire|	영감을 주다|\r\n"
				+ "install|	설치하다|\r\n"
				+ "instance|	실례|\r\n"
				+ "instant|	즉시의|\r\n"
				+ "instead|	그 대신에|\r\n"
				+ "instinct|	본능|\r\n"
				+ "institute|	만들다|\r\n"
				+ "instruct|	가르치다|\r\n"
				+ "instrument|	기구|\r\n"
				+ "insult|	모욕하다|\r\n"
				+ "insure|	보증하다|\r\n"
				+ "intellectual|	지적인|\r\n"
				+ "intelligent|	지적인|\r\n"
				+ "intend|	-할 작정이다|\r\n"
				+ "intense|	강렬한|\r\n"
				+ "intent|	의향|\r\n"
				+ "interact|	서로 작용하다|\r\n"
				+ "interest|	흥미|\r\n"
				+ "interfere|	간섭하다|\r\n"
				+ "intermediate|	중간의 중간물|\r\n"
				+ "internal|	내부의|\r\n"
				+ "international|	국제적인|\r\n"
				+ "interpret|	해석하다|\r\n"
				+ "interrupt|	훼방놓다|\r\n"
				+ "interval|	간격|\r\n"
				+ "intimate|	친밀한|\r\n"
				+ "invade|	침입하다|\r\n"
				+ "invent|	발명하다|\r\n"
				+ "invest|	투자하다|\r\n"
				+ "investigate|	조사하다|\r\n"
				+ "involve|	말아넣다|\r\n"
				+ "iron|	쇠|\r\n"
				+ "irony|	반어|\r\n"
				+ "irritate|	노하게 하다|\r\n"
				+ "island|	섬|\r\n"
				+ "isolate|	고립시키다|\r\n"
				+ "item|	조항|\r\n"
				+ "jail|	교도소|\r\n"
				+ "jar|	(아가리가 넓은)항아리|\r\n"
				+ "jaw|	턱|\r\n"
				+ "jet|	(가스등의)분출|\r\n"
				+ "jog|	살짝 밀다 덜커덕 움직이다 고르지 않음|\r\n"
				+ "joint|	이음매|\r\n"
				+ "joke|	농담|\r\n"
				+ "journal|	일간신문|\r\n"
				+ "journey|	여행|\r\n"
				+ "judge|	재판관|\r\n"
				+ "junior|	손아래사람|\r\n"
				+ "jury|	배심|\r\n"
				+ "justice|	정의|\r\n"
				+ "justify|	옳다고 하다|\r\n"
				+ "kit|	연장통|\r\n"
				+ "knee|	무릎|\r\n"
				+ "knight|	(중세의)기사|\r\n"
				+ "knock|	치다|\r\n"
				+ "label|	라벨|\r\n"
				+ "labor|	노동|\r\n"
				+ "laboratory|	실험실|\r\n"
				+ "lack|	결핍|\r\n"
				+ "ladder|	사닥다리|\r\n"
				+ "lamb|	어린 양|\r\n"
				+ "lamp|	등|\r\n"
				+ "landscape|	풍경|\r\n"
				+ "lane|	좁은길|\r\n"
				+ "language|	언어|\r\n"
				+ "lap|	무릎|\r\n"
				+ "latter|	뒤쪽의|\r\n"
				+ "laugh|	(소리내어)웃다|\r\n"
				+ "launch|	진수시키다|\r\n"
				+ "laundry|	세탁물|\r\n"
				+ "law|	법률|\r\n"
				+ "lawn|	잔디밭|\r\n"
				+ "lawyer|	법률가|\r\n"
				+ "lay|	눕히다|\r\n"
				+ "layer|	층|\r\n"
				+ "lead|	이끌다|\r\n"
				+ "leak|	샘|\r\n"
				+ "lean|	기대다|\r\n"
				+ "leap|	껑충 뛰다|\r\n"
				+ "leather|	무두질한 가죽|\r\n"
				+ "leave|	남기고가다|\r\n"
				+ "lecture|	강의|\r\n"
				+ "legal|	법률상의|\r\n"
				+ "legend|	전설|\r\n"
				+ "leisure|	틈|\r\n"
				+ "lend|	빌리다|\r\n"
				+ "let|	시키다|\r\n"
				+ "level|	수평의|\r\n"
				+ "liberal|	자유주의의|\r\n"
				+ "liberty|	자유|\r\n"
				+ "license|	면허|\r\n"
				+ "lid|	뚜껑|\r\n"
				+ "lift|	끌어올리다|\r\n"
				+ "likely|	있을 법한|\r\n"
				+ "likewise|	같이, 마찬가지로|\r\n"
				+ "limit|	한계|\r\n"
				+ "linguistic|	말의|\r\n"
				+ "link|	사슬의 고리|\r\n"
				+ "liquid|	액체|\r\n"
				+ "list|	일람표|\r\n"
				+ "literature|	문학|\r\n"
				+ "load|	짐|\r\n"
				+ "loan|	대부|\r\n"
				+ "local|	장소의|\r\n"
				+ "locate|	관청 등을 두다|\r\n"
				+ "lock|	자물쇠|\r\n"
				+ "log|	통나무|\r\n"
				+ "logic|	논리학|\r\n"
				+ "loose|	풀어진|\r\n"
				+ "lose|	잃다|\r\n"
				+ "loss|	잃음|\r\n"
				+ "lot|	제비|\r\n"
				+ "loud|	시끄러운|\r\n"
				+ "lounge|	빈둥거리다|\r\n"
				+ "loyal|	충성스러운|\r\n"
				+ "luxury|	사치|\r\n"
				+ "machine|	기계|\r\n"
				+ "magazine|	잡지|\r\n"
				+ "magnet|	자석|\r\n"
				+ "main|	주요한|\r\n"
				+ "maintain|	계속하다|\r\n"
				+ "major|	큰쪽의|\r\n"
				+ "majority|	대다수|\r\n"
				+ "male|	남성의|\r\n"
				+ "manage|	관리하다|\r\n"
				+ "manner|	방법|\r\n"
				+ "manufacture|	제조하다|\r\n"
				+ "margin|	가장자리|\r\n"
				+ "marine|	바다의|\r\n"
				+ "mark|	표|\r\n"
				+ "marvel|	경이|\r\n"
				+ "mass|	덩어리|\r\n"
				+ "master|	장|\r\n"
				+ "match|	성냥|\r\n"
				+ "mate|	상대|\r\n"
				+ "material|	원료|\r\n"
				+ "matter|	물질|\r\n"
				+ "mature|	익은|\r\n"
				+ "maximum|	최고점|\r\n"
				+ "maybe|	아마|\r\n"
				+ "mayor|	시장|\r\n"
				+ "meal|	식사|\r\n"
				+ "mean|	의미하다|\r\n"
				+ "meantime|	그동안 그 사이에|\r\n"
				+ "measure|	재다|\r\n"
				+ "mechanic|	직공|\r\n"
				+ "mechanism|	(기계)장치|\r\n"
				+ "mediate|	중재하다|\r\n"
				+ "medical|	의학의|\r\n"
				+ "medicine|	약|\r\n"
				+ "medium|	중간|\r\n"
				+ "melt|	녹다|\r\n"
				+ "mental|	마음의|\r\n"
				+ "mention|	말하다|\r\n"
				+ "merchant|	상인|\r\n"
				+ "merit|	장점|\r\n"
				+ "mess|	혼란|\r\n"
				+ "metal|	금속|\r\n"
				+ "method|	방법|\r\n"
				+ "microphone|	확성기|\r\n"
				+ "microwave|	극초단파 전자레인지로 요리하다|\r\n"
				+ "mild|	온후한|\r\n"
				+ "military|	군의|\r\n"
				+ "mill|	멧돌|\r\n"
				+ "million|	백만|\r\n"
				+ "miner|	광산업자|\r\n"
				+ "mineral|	광물|\r\n"
				+ "minimal|	최소(한도)의|\r\n"
				+ "minimum|	최소 한도|\r\n"
				+ "ministry|	장관(목사)의 직(소임)|\r\n"
				+ "minor|	작은 편의|\r\n"
				+ "minute|	분|\r\n"
				+ "miracle|	기적|\r\n"
				+ "missile|	미사일|\r\n"
				+ "mission|	사명|\r\n"
				+ "mistake|	틀리다|\r\n"
				+ "mix|	섞다|\r\n"
				+ "mobile|	움직이기 쉬운|\r\n"
				+ "mode|	방법|\r\n"
				+ "modern|	현대의|\r\n"
				+ "moisture|	습기|\r\n"
				+ "moment|	순간|\r\n"
				+ "monitor|	충고자|\r\n"
				+ "monster|	괴물|\r\n"
				+ "mood|	(일시적인)기분|\r\n"
				+ "moral|	도덕의|\r\n"
				+ "moreover|	그 위에|\r\n"
				+ "motion|	운동|\r\n"
				+ "motive|	동기|\r\n"
				+ "mount|	산|\r\n"
				+ "mud|	진흙|\r\n"
				+ "multiple|	복합의|\r\n"
				+ "multiply|	늘리다|\r\n"
				+ "murder|	살인|\r\n"
				+ "muscle|	근육|\r\n"
				+ "mushroom|	버섯|\r\n"
				+ "myth|	신화|\r\n"
				+ "nail|	손톱|\r\n"
				+ "naked|	발가벗은|\r\n"
				+ "narrate|	이야기하다|\r\n"
				+ "narrow|	좁은|\r\n"
				+ "native|	타고난|\r\n"
				+ "navy|	해군(력)|\r\n"
				+ "neat|	산뜻한|\r\n"
				+ "necessary|	필요한|\r\n"
				+ "needle|	바늘 바늘로 꿰매다 바느질하다 아슬아슬한|\r\n"
				+ "negative|	부정적인|\r\n"
				+ "neglect|	게을리 하다|\r\n"
				+ "negotiate|	교섭하다|\r\n"
				+ "neighbor|	이웃사람(나라)|\r\n"
				+ "neither|	(둘중)어느쪽도 -아니다 -도 아니다|\r\n"
				+ "nephew|	조카|\r\n"
				+ "nervous|	신경의|\r\n"
				+ "nest|	보금자리|\r\n"
				+ "net|	그물|\r\n"
				+ "network|	그물세공|\r\n"
				+ "neutral|	중립의|\r\n"
				+ "nevertheless|	그럼에도 불구하고|\r\n"
				+ "nightmare|	악몽|\r\n"
				+ "noble|	고귀한|\r\n"
				+ "nobody|	아무도 -않다 하찮은 사람|\r\n"
				+ "nod|	끄덕이다|\r\n"
				+ "noise|	소리|\r\n"
				+ "none|	아무도(조금도)-않다 조금도(결코)-않다|\r\n"
				+ "nonsense|	허튼 소리|\r\n"
				+ "nor|	-도 또한-않다|\r\n"
				+ "normal|	표준(의)|\r\n"
				+ "notice|	통지, 통보|\r\n"
				+ "novel|	소설|\r\n"
				+ "nowadays|	오늘날에는, 요즈음에는|\r\n"
				+ "nowhere|	아무데도 …없다|\r\n"
				+ "nuclear|	핵의, 핵을 형성하는 원자핵의|\r\n"
				+ "nut|	견과|\r\n"
				+ "oak|	참나무|\r\n"
				+ "obey|	따르다|\r\n"
				+ "object|	사물|\r\n"
				+ "objective|	객관적인|\r\n"
				+ "observe|	관찰하다|\r\n"
				+ "obtain|	얻다|\r\n"
				+ "obvious|	명백한|\r\n"
				+ "occasion|	경우|\r\n"
				+ "occupation|	일직업|\r\n"
				+ "occupy|	차지하다|\r\n"
				+ "occur|	일어나다|\r\n"
				+ "odd|	묘한|\r\n"
				+ "offend|	성나게 하다|\r\n"
				+ "offer|	권하다|\r\n"
				+ "officer|	공무원|\r\n"
				+ "official|	공무원|\r\n"
				+ "olive|	올리브나무|\r\n"
				+ "once|	한번|\r\n"
				+ "operate|	움직이다|\r\n"
				+ "opinion|	의견|\r\n"
				+ "opportunity|	기회|\r\n"
				+ "oppose|	반대하다|\r\n"
				+ "optimist|	낙천가|\r\n"
				+ "option|	선택(권의 자유)|\r\n"
				+ "oral|	구두의|\r\n"
				+ "orchestra|	관현악단|\r\n"
				+ "order|	순서|\r\n"
				+ "ordinary|	보통의|\r\n"
				+ "organ|	(생물의)기관|\r\n"
				+ "organic|	유기체의|\r\n"
				+ "organize|	조직하다|\r\n"
				+ "orient|	동양 동양의 동쪽으로 향하게 하다|\r\n"
				+ "origin|	기원|\r\n"
				+ "other|	다른 다른 것 그렇지 않고|\r\n"
				+ "otherwise|	딴 방법으로는|\r\n"
				+ "ought|	au해야만 하다|\r\n"
				+ "outcome|	결과|\r\n"
				+ "outline|	윤곽|\r\n"
				+ "output|	산출|\r\n"
				+ "outstanding|	눈에 띄는|\r\n"
				+ "overall|	포괄(전면)적인 덧옷|\r\n"
				+ "overcome|	이기다|\r\n"
				+ "overhead|	머리위에 머리 위의|\r\n"
				+ "overlap|	겹치다|\r\n"
				+ "overlook|	내려다 보다|\r\n"
				+ "overnight|	전날밤의|\r\n"
				+ "oversea|	해외(로부터)의|\r\n"
				+ "owe|	지불할 의무가 있다|\r\n"
				+ "own|	자기자신의 소유하다|\r\n"
				+ "pace|	한걸음|\r\n"
				+ "pack|	꾸러미|\r\n"
				+ "packet|	다발|\r\n"
				+ "pad|	(및에)덧대는 것|\r\n"
				+ "pain|	고통|\r\n"
				+ "pair|	한쌍|\r\n"
				+ "pale|	창백한|\r\n"
				+ "palm|	손바닥|\r\n"
				+ "pan|	남비 사금 등을 남비로 가려내다|\r\n"
				+ "panic|	돌연한공포|\r\n"
				+ "paragraph|	(문장의)절|\r\n"
				+ "pardon|	용서하다 용서|\r\n"
				+ "participate|	참가하다|\r\n"
				+ "particular|	특수한|\r\n"
				+ "passage|	통행, 통과|\r\n"
				+ "passenger|	승객|\r\n"
				+ "passion|	정열|\r\n"
				+ "passport|	여권|\r\n"
				+ "past|	과거|\r\n"
				+ "path|	작은 길|\r\n"
				+ "patient|	인내심이 강한 환자|\r\n"
				+ "pattern|	모범|\r\n"
				+ "pause|	중지|\r\n"
				+ "peak|	(뾰족한)끝|\r\n"
				+ "peel|	껍질을 벗기다 벗어지다 껍질|\r\n"
				+ "peer|	동료|\r\n"
				+ "penalty|	벌|\r\n"
				+ "pepper|	고추|\r\n"
				+ "per|	-에 의하여|\r\n"
				+ "perceive|	지각하다|\r\n"
				+ "perfect|	완전한|\r\n"
				+ "perform|	다하다|\r\n"
				+ "perhaps|	아마|\r\n"
				+ "period|	시간|\r\n"
				+ "permanent|	영구의|\r\n"
				+ "permit|	허가하다|\r\n"
				+ "person|	사람|\r\n"
				+ "personality|	개성|\r\n"
				+ "persuade|	설득하다|\r\n"
				+ "pet|	애완동물|\r\n"
				+ "phenomenon|	현상|\r\n"
				+ "philosophy|	철학|\r\n"
				+ "photograph|	사진 촬영하다|\r\n"
				+ "phrase|	구|\r\n"
				+ "physical|	물질의|\r\n"
				+ "physics|	물리학|\r\n"
				+ "piece|	한 조각|\r\n"
				+ "pile|	쌓아 올린 것|\r\n"
				+ "pill|	알약|\r\n"
				+ "pin|	핀 핀으로 꽂다|\r\n"
				+ "pine|	소나무 수척해 지다|\r\n"
				+ "pioneer|	개척자|\r\n"
				+ "pity|	불쌍히 여김|\r\n"
				+ "plain|	분명한|\r\n"
				+ "planet|	행성|\r\n"
				+ "plant|	실물|\r\n"
				+ "plate|	판|\r\n"
				+ "platform|	단|\r\n"
				+ "pleasant|	기분 좋은|\r\n"
				+ "pleasure|	즐거움|\r\n"
				+ "plenty|	많음|\r\n"
				+ "plot|	음모|\r\n"
				+ "plus|	더하기의 -외에|\r\n"
				+ "poem|	시|\r\n"
				+ "poet|	시인|\r\n"
				+ "poison|	독|\r\n"
				+ "polar|	남극의|\r\n"
				+ "pole|	폴란드사람|\r\n"
				+ "policy|	정책|\r\n"
				+ "polite|	공손한|\r\n"
				+ "politics|	정치|\r\n"
				+ "poll|	투표|\r\n"
				+ "pollute|	-을 더럽히다|\r\n"
				+ "pond|	못, 연못|\r\n"
				+ "pool|	판돈|\r\n"
				+ "pop|	팝|\r\n"
				+ "popular|	민중 의, 대중의|\r\n"
				+ "population|	인구|\r\n"
				+ "pork|	돼지고기|\r\n"
				+ "port|	항구, 항만, 상항|\r\n"
				+ "portrait|	초상|\r\n"
				+ "pose|	자세, 포즈  마음가짐  꾸민 태도|\r\n"
				+ "position|	위치|\r\n"
				+ "positive|	명확한, 의문의 여지가 없는, 부정할 수 없는|\r\n"
				+ "possess|	소유하다|\r\n"
				+ "possible|	가능한|\r\n"
				+ "post|	기둥|\r\n"
				+ "poster|	포스터|\r\n"
				+ "pot|	단지|\r\n"
				+ "potential|	가능한|\r\n"
				+ "pour|	따르다|\r\n"
				+ "powder|	가루|\r\n"
				+ "practical|	실제의|\r\n"
				+ "practice|	연습|\r\n"
				+ "praise|	칭찬|\r\n"
				+ "pray|	빌다|\r\n"
				+ "precious|	비싼|\r\n"
				+ "precise|	정확한|\r\n"
				+ "predict|	예언하다, 예보하다 예언하다|\r\n"
				+ "prefer|	오히려 …을 좋아하다,|\r\n"
				+ "pregnant|	임신한 충만한|\r\n"
				+ "prepare|	준비하 다, 마련하다, 채비를 갖추다|\r\n"
				+ "prescribe|	명령하다, 지령하다|\r\n"
				+ "presence|	존재, 현존, 실재  출석, 임석, 참석|\r\n"
				+ "preserve|	보호하다, 지키다|\r\n"
				+ "president|	대통령 회장|\r\n"
				+ "press|	강제로 모집하다|\r\n"
				+ "pretend|	핑계삼다|\r\n"
				+ "prevent|	막다, 방해하다|\r\n"
				+ "previous|	앞의, 이전의|\r\n"
				+ "prey|	먹이|\r\n"
				+ "price|	값, 가격, 대가, 정가|\r\n"
				+ "pride|	자존심|\r\n"
				+ "priest|	성직자|\r\n"
				+ "primary|	첫째의, 제1위의, 수위의 초등의, 초보의|\r\n"
				+ "prime|	수위의, 최초의, 원시적인|\r\n"
				+ "primitive|	원시의, 초기의|\r\n"
				+ "principal|	주요한, 주된, 제일의, 앞장서는|\r\n"
				+ "principle|	원리, 원칙, 법칙, 공리|\r\n"
				+ "prison|	교도소|\r\n"
				+ "privacy|	남의 눈을 피함, 은거, 은둔, 은퇴 생활 사생활|\r\n"
				+ "private|	사적인, 사사로운, 개인에 속한|\r\n"
				+ "probably|	아마, 십중팔구|\r\n"
				+ "proceed|	나아가다, 가다|\r\n"
				+ "process|	진행, 작용|\r\n"
				+ "produce|	생산하다, 산출하다, 생기게 하다,|\r\n"
				+ "profession|	직업 공언, 선언, 고백|\r\n"
				+ "professor|	교수|\r\n"
				+ "profit|	이익, 이득, 벌이|\r\n"
				+ "progress|	진행, 전진, 진척  진보, 향상, 발달, 발전|\r\n"
				+ "promise|	약속, 서약, 계약|\r\n"
				+ "promote|	승진시키다 진행시키다,|\r\n"
				+ "pronounce|	발음하다, 음독하다|\r\n"
				+ "proof|	증명|\r\n"
				+ "proper|	고유의, 독특한, 본연의,  특유한|\r\n"
				+ "property|	재산, 자산|\r\n"
				+ "propose|	제의하다, 제출하다 추천하다, 지명하다|\r\n"
				+ "prospect|	전망, 조망, 경치|\r\n"
				+ "protect|	보호하다, 막다, 지키다, 비호하다|\r\n"
				+ "protein|	IG1s|\r\n"
				+ "protest|	단언하다|\r\n"
				+ "proud|	뽐내는, 자랑하는 자긍하는, 영광 으로 여기는|\r\n"
				+ "prove|	시험하다, 실험하다, 경험하다, 시험해 보다|\r\n"
				+ "provide|	준비하다, 미리 …에 대비하다  규정하다|\r\n"
				+ "province|	주, 성, 도  범위, 영역, 분야|\r\n"
				+ "psychology|	심리학|\r\n"
				+ "pub|	펍|\r\n"
				+ "public|	심리, 심리 상태|\r\n"
				+ "publish|	발표 하다, 널리 알리다|\r\n"
				+ "pull|	끌다, 당기다, 끌어 당기다, 잡아 끌다|\r\n"
				+ "pump|	펌프스   댄스용 구두|\r\n"
				+ "punch|	주먹질, 펀치  힘, 활기|\r\n"
				+ "punish|	벌하다, 응징하다, 처형하다|\r\n"
				+ "pupil|	흔히 국민학교 중학교 학생|\r\n"
				+ "purchase|	사다, 구입하다|\r\n"
				+ "pure|	순수한  깨끗한, 순전한, 결백한|\r\n"
				+ "purple|	자줏빛의  새빨간  제왕의|\r\n"
				+ "purpose|	목적|\r\n"
				+ "pursue|	쫓다, 추적하다, 몰다|\r\n"
				+ "qualify|	자격을 부여하다|\r\n"
				+ "quality|	질|\r\n"
				+ "quantity|	양|\r\n"
				+ "quarter|	1|\r\n"
				+ "quit|	(의무,책임을)벗어난 떠나다|\r\n"
				+ "quite|	아주|\r\n"
				+ "racial|	인종(상)의|\r\n"
				+ "rail|	가로장|\r\n"
				+ "raise|	올리다|\r\n"
				+ "random|	닥치는 대로의|\r\n"
				+ "range|	줄|\r\n"
				+ "rank|	열|\r\n"
				+ "rapid|	빠른|\r\n"
				+ "rare|	희귀한|\r\n"
				+ "rat|	쥐|\r\n"
				+ "rate|	율|\r\n"
				+ "rather|	오히려|\r\n"
				+ "raw|	날것의|\r\n"
				+ "reach|	도착하다|\r\n"
				+ "react|	반응을 나타내다|\r\n"
				+ "real|	실재하는|\r\n"
				+ "realize|	깨닫다|\r\n"
				+ "reason|	이성|\r\n"
				+ "recall|	되부르다|\r\n"
				+ "receipt|	수령|\r\n"
				+ "receive|	받다|\r\n"
				+ "recent|	최근의|\r\n"
				+ "reception|	받음|\r\n"
				+ "recipe|	조리법|\r\n"
				+ "recognize|	인정하다|\r\n"
				+ "recommend|	추천하다|\r\n"
				+ "record|	기록하다|\r\n"
				+ "recover|	되찾다|\r\n"
				+ "recycle|	재생 이용하다|\r\n"
				+ "reduce|	줄이다|\r\n"
				+ "refer|	조회시키다|\r\n"
				+ "reflect|	반사하다|\r\n"
				+ "reform|	개정(개혁)하다|\r\n"
				+ "refrigerator|	냉장고|\r\n"
				+ "refuse|	거절하다|\r\n"
				+ "regard|	주목해서 보다|\r\n"
				+ "region|	지방|\r\n"
				+ "register|	기록|\r\n"
				+ "regret|	유감|\r\n"
				+ "regular|	규칙적인|\r\n"
				+ "reject|	거절하다|\r\n"
				+ "relate|	이야기하다|\r\n"
				+ "relative|	친척|\r\n"
				+ "relax|	늦추다|\r\n"
				+ "release|	도와주다|\r\n"
				+ "relieve|	구출하다|\r\n"
				+ "religion|	종교|\r\n"
				+ "rely|	믿다|\r\n"
				+ "remain|	남다|\r\n"
				+ "remark|	깨닫다|\r\n"
				+ "remedy|	치료|\r\n"
				+ "remind|	생각나게 하다|\r\n"
				+ "remote|	먼|\r\n"
				+ "remove|	옮기다|\r\n"
				+ "rent|	지대|\r\n"
				+ "repair|	수선(수정)하다|\r\n"
				+ "repeat|	반복하다|\r\n"
				+ "replace|	되돌려 놓다|\r\n"
				+ "reply|	대답하다|\r\n"
				+ "report|	보고|\r\n"
				+ "represent|	표현(묘사)하다|\r\n"
				+ "republic|	공화국|\r\n"
				+ "request|	부탁하다|\r\n"
				+ "require|	요구하다|\r\n"
				+ "rescue|	구하다|\r\n"
				+ "research|	연구|\r\n"
				+ "resemble|	닮다|\r\n"
				+ "reserve|	따로 두다|\r\n"
				+ "resist|	저항하다|\r\n"
				+ "resolve|	분해하다|\r\n"
				+ "resort|	(자주)가다|\r\n"
				+ "resource|	자원|\r\n"
				+ "respect|	존경하다|\r\n"
				+ "respond|	대답하다|\r\n"
				+ "responsible|	책임을 져야할|\r\n"
				+ "rest|	휴식|\r\n"
				+ "restore|	반환하다|\r\n"
				+ "result|	결과|\r\n"
				+ "retire|	퇴직하다|\r\n"
				+ "reveal|	나타내다|\r\n"
				+ "review|	재조사|\r\n"
				+ "revise|	교정하다|\r\n"
				+ "revive|	소생하다|\r\n"
				+ "revolution|	혁명|\r\n"
				+ "reward|	보수|\r\n"
				+ "rhythm|	율동|\r\n"
				+ "rice|	쌀|\r\n"
				+ "ride|	타다|\r\n"
				+ "rise|	올리다|\r\n"
				+ "risk|	위험 걸다|\r\n"
				+ "rival|	경쟁자 경쟁하는 경쟁하다|\r\n"
				+ "roast|	불에 쬐어 굽다 불고기 구운|\r\n"
				+ "rob|	강탈하다, 약탈하다, 빼앗다|\r\n"
				+ "role|	(배우의)역|\r\n"
				+ "roll|	구르다|\r\n"
				+ "romantic|	전기소설적인|\r\n"
				+ "root|	뿌리|\r\n"
				+ "rope|	새끼|\r\n"
				+ "rough|	거친|\r\n"
				+ "round|	둥근 원 돌아서|\r\n"
				+ "route|	길|\r\n"
				+ "routine|	정해진 일|\r\n"
				+ "row|	줄|\r\n"
				+ "royal|	왕의|\r\n"
				+ "rub|	마찰하다|\r\n"
				+ "rubber|	맛사지사|\r\n"
				+ "rude|	버릇없는|\r\n"
				+ "ruin|	파멸|\r\n"
				+ "rule|	규칙|\r\n"
				+ "rumor|	소문|\r\n"
				+ "rural|	시골의|\r\n"
				+ "rush|	돌진하다|\r\n"
				+ "sacred|	신성한|\r\n"
				+ "sacrifice|	희생|\r\n"
				+ "sail|	돛|\r\n"
				+ "salary|	봉급 봉급을 주다|\r\n"
				+ "satellite|	위성|\r\n"
				+ "satisfy|	만족시키다|\r\n"
				+ "scale|	비늘(모양의 것)|\r\n"
				+ "scan|	시의 운율을살피다|\r\n"
				+ "scandal|	추문|\r\n"
				+ "scare|	위협하다|\r\n"
				+ "scene|	장면|\r\n"
				+ "scheme|	계획|\r\n"
				+ "scholar|	학자|\r\n"
				+ "scold|	꾸짖다 잔소리 심한 사람|\r\n"
				+ "scramble|	기다|\r\n"
				+ "scratch|	할퀴다, 할퀴어 상처 를 내다  긁다|\r\n"
				+ "scream|	비명을 지르다|\r\n"
				+ "screen|	병풍|\r\n"
				+ "seal|	인장|\r\n"
				+ "search|	찾다|\r\n"
				+ "seat|	좌석|\r\n"
				+ "secret|	비밀의|\r\n"
				+ "secretary|	비서|\r\n"
				+ "sector|	부채꼴|\r\n"
				+ "secure|	안전한|\r\n"
				+ "seed|	씨앗|\r\n"
				+ "seek|	찾다|\r\n"
				+ "seem|	-으로 보이다|\r\n"
				+ "select|	고르다|\r\n"
				+ "self|	자기|\r\n"
				+ "senior|	연상의|\r\n"
				+ "sensation|	감각|\r\n"
				+ "sense|	감각|\r\n"
				+ "sensible|	분별있는|\r\n"
				+ "sentence|	문장|\r\n"
				+ "separate|	분리된|\r\n"
				+ "series|	연속|\r\n"
				+ "serious|	진지한|\r\n"
				+ "serve|	섬기다|\r\n"
				+ "session|	개회|\r\n"
				+ "settle|	등받이가 높은 긴 의자 놓다|\r\n"
				+ "several|	수개의|\r\n"
				+ "severe|	호된|\r\n"
				+ "sew|	꿰매다|\r\n"
				+ "sex|	성|\r\n"
				+ "shade|	그늘|\r\n"
				+ "shadow|	그림자|\r\n"
				+ "shake|	흔들어 움직이다|\r\n"
				+ "shall|	au-하겠다|\r\n"
				+ "shallow|	얕은 얕은 곳 얕아지다|\r\n"
				+ "shame|	부끄럼|\r\n"
				+ "shape|	모양|\r\n"
				+ "share|	몫|\r\n"
				+ "sharp|	날카로운|\r\n"
				+ "shave|	깎다|\r\n"
				+ "sheep|	양|\r\n"
				+ "sheet|	깔천|\r\n"
				+ "shelf|	선반|\r\n"
				+ "shell|	겉껍질|\r\n"
				+ "shift|	옮기다|\r\n"
				+ "shine|	빛나다|\r\n"
				+ "shoot|	쏘다|\r\n"
				+ "shore|	물가|\r\n"
				+ "shoulder|	어깨|\r\n"
				+ "shout|	외치다|\r\n"
				+ "shower|	소나기 빗발치듯 퍼붓다(쏟다)|\r\n"
				+ "shut|	닫다|\r\n"
				+ "sigh|	한숨|\r\n"
				+ "sight|	광경|\r\n"
				+ "sign|	부호|\r\n"
				+ "significant|	중요한|\r\n"
				+ "silent|	조용한|\r\n"
				+ "silk|	비단|\r\n"
				+ "silly|	어리석은 바보|\r\n"
				+ "silver|	은|\r\n"
				+ "similar|	유사한|\r\n"
				+ "simple|	단일의|\r\n"
				+ "sin|	사인|\r\n"
				+ "since|	-이래|\r\n"
				+ "single|	단 하나의|\r\n"
				+ "sink|	가라앉다|\r\n"
				+ "site|	부지|\r\n"
				+ "situation|	장소|\r\n"
				+ "skill|	숙련|\r\n"
				+ "skip|	도약|\r\n"
				+ "slave|	노예 노예처럼 일하다|\r\n"
				+ "slice|	얇은조각|\r\n"
				+ "slide|	미끄러지다|\r\n"
				+ "slim|	호리호리한|\r\n"
				+ "slip|	(때가)어느덧 지나가다|\r\n"
				+ "smash|	박살내다|\r\n"
				+ "smoke|	연기|\r\n"
				+ "smooth|	매끄러운|\r\n"
				+ "snake|	뱀|\r\n"
				+ "snap|	덥석 물다|\r\n"
				+ "soak|	담그다|\r\n"
				+ "soap|	비누 비누로 씻다|\r\n"
				+ "social|	사회의|\r\n"
				+ "society|	사회|\r\n"
				+ "sociology|	사회학|\r\n"
				+ "software|	소프트웨어|\r\n"
				+ "soil|	흙|\r\n"
				+ "soldier|	군인|\r\n"
				+ "solid|	고체의|\r\n"
				+ "solo|	독주|\r\n"
				+ "solve|	해결하다|\r\n"
				+ "somewhat|	약간|\r\n"
				+ "soon|	얼마 안 가서|\r\n"
				+ "sore|	슬픈|\r\n"
				+ "sort|	종류|\r\n"
				+ "soul|	혼|\r\n"
				+ "source|	원천|\r\n"
				+ "spare|	여분의|\r\n"
				+ "spark|	불꽃|\r\n"
				+ "special|	특별한|\r\n"
				+ "species|	종|\r\n"
				+ "specific|	특정한|\r\n"
				+ "speech|	연설|\r\n"
				+ "spell|	철자하다|\r\n"
				+ "spend|	소비하다|\r\n"
				+ "spin|	잣다|\r\n"
				+ "spirit|	정신|\r\n"
				+ "spoil|	망쳐놓다|\r\n"
				+ "spot|	장소|\r\n"
				+ "spread|	펴다|\r\n"
				+ "square|	정사각형의|\r\n"
				+ "squeeze|	압착하다|\r\n"
				+ "stable|	안정된|\r\n"
				+ "stage|	무대|\r\n"
				+ "stain|	더럽히다|\r\n"
				+ "stairs|	계단|\r\n"
				+ "stamp|	도장|\r\n"
				+ "standard|	표준|\r\n"
				+ "stare|	응시하다|\r\n"
				+ "state|	상태|\r\n"
				+ "station|	역|\r\n"
				+ "statue|	조상|\r\n"
				+ "status|	신분|\r\n"
				+ "steady|	확고한|\r\n"
				+ "steal|	훔치다|\r\n"
				+ "steam|	증기|\r\n"
				+ "steel|	강철|\r\n"
				+ "stem|	줄기|\r\n"
				+ "step|	걷다|\r\n"
				+ "stick|	나무토막|\r\n"
				+ "still|	소리가 없는 아직(도)|\r\n"
				+ "stock|	줄기|\r\n"
				+ "stomach|	위|\r\n"
				+ "storm|	폭풍|\r\n"
				+ "stove|	stave의 과거(분사)|\r\n"
				+ "straight|	곧은|\r\n"
				+ "strange|	이상한|\r\n"
				+ "strategy|	용병학|\r\n"
				+ "straw|	짚|\r\n"
				+ "stream|	시내|\r\n"
				+ "stretch|	뻗치다|\r\n"
				+ "strict|	엄중한|\r\n"
				+ "strike|	치다|\r\n"
				+ "string|	끈|\r\n"
				+ "stripe|	줄무늬|\r\n"
				+ "structure|	구조|\r\n"
				+ "struggle|	버둥거리다|\r\n"
				+ "stuff|	재료|\r\n"
				+ "subject|	복종시키다|\r\n"
				+ "submarine|	잠수함|\r\n"
				+ "suburb|	교외|\r\n"
				+ "succeed|	성공하다|\r\n"
				+ "such|	이러한|\r\n"
				+ "sudden|	별안간의|\r\n"
				+ "suffer|	경험하다|\r\n"
				+ "sufficient|	충분한|\r\n"
				+ "suggest|	암시하다|\r\n"
				+ "suicide|	자살 자살하다|\r\n"
				+ "suit|	소송|\r\n"
				+ "sum|	총계|\r\n"
				+ "summary|	요약|\r\n"
				+ "summit|	꼭대기|\r\n"
				+ "super|	임시고용배우|\r\n"
				+ "superb|	장려한|\r\n"
				+ "superior|	뛰어난|\r\n"
				+ "supply|	공급하다|\r\n"
				+ "support|	지탱하다|\r\n"
				+ "suppose|	상상하다|\r\n"
				+ "sure|	확신하는, 확실한 , 틀림없는|\r\n"
				+ "surface|	표면|\r\n"
				+ "surgery|	외과|\r\n"
				+ "surprise|	놀람|\r\n"
				+ "surround|	에워싸다|\r\n"
				+ "survey|	둘러보다|\r\n"
				+ "survive|	살아 남다|\r\n"
				+ "suspect|	짐작하다|\r\n"
				+ "swallow|	삼키다|\r\n"
				+ "sweat|	땀|\r\n"
				+ "sweet|	단|\r\n"
				+ "swing|	흔들리다|\r\n"
				+ "switch|	회초리|\r\n"
				+ "symbol|	상징|\r\n"
				+ "sympathy|	동정|\r\n"
				+ "symphony|	교향곡|\r\n"
				+ "symptom|	조짐|\r\n"
				+ "system|	조직|\r\n"
				+ "tackle|	고패|\r\n"
				+ "tag|	손잡이가죽|\r\n"
				+ "tale|	이야기|\r\n"
				+ "talent|	재주|\r\n"
				+ "tap|	가볍게 치기|\r\n"
				+ "target|	과녁|\r\n"
				+ "task|	일|\r\n"
				+ "tattoo|	귀영나팔|\r\n"
				+ "tax|	세금|\r\n"
				+ "tea|	차|\r\n"
				+ "tear|	눈물|\r\n"
				+ "teenage|	10대|\r\n"
				+ "temperature|	온도|\r\n"
				+ "temple|	관자놀이|\r\n"
				+ "tend|	(-의)경향이 있다|\r\n"
				+ "tender|	제공|\r\n"
				+ "tense|	시제|\r\n"
				+ "term|	기간|\r\n"
				+ "terminal|	종점의|\r\n"
				+ "terrible|	무시무시한|\r\n"
				+ "terrific|	무서운|\r\n"
				+ "territory|	영토|\r\n"
				+ "text|	원문|\r\n"
				+ "theater|	=theatre 극장|\r\n"
				+ "theme|	논제|\r\n"
				+ "then|	그때|\r\n"
				+ "theory|	이론|\r\n"
				+ "therefore|	그런 까닭에|\r\n"
				+ "thick|	두꺼운|\r\n"
				+ "thief|	도둑|\r\n"
				+ "thin|	얇은|\r\n"
				+ "thorough|	완전한|\r\n"
				+ "though|	-임에도 불구하고 그러나|\r\n"
				+ "thousand|	천|\r\n"
				+ "threat|	협박|\r\n"
				+ "thrill|	오싹하다 오싹함|\r\n"
				+ "throat|	목|\r\n"
				+ "through|	(-을)통하여 통하여 직통의|\r\n"
				+ "throw|	던지다|\r\n"
				+ "thumb|	엄지손가락 엄지손가락으로 만지다|\r\n"
				+ "thus|	이렇게|\r\n"
				+ "tide|	조수|\r\n"
				+ "tidy|	말쑥한|\r\n"
				+ "tie|	매다|\r\n"
				+ "tight|	단단한|\r\n"
				+ "till|	-까지|\r\n"
				+ "tin|	주석|\r\n"
				+ "tiny|	자그마한|\r\n"
				+ "tip|	끝|\r\n"
				+ "tire|	피로하게 하다|\r\n"
				+ "tissue|	조직|\r\n"
				+ "title|	표제|\r\n"
				+ "tobacco|	담배|\r\n"
				+ "toe|	발가락|\r\n"
				+ "toilet|	화장실|\r\n"
				+ "tone|	음조|\r\n"
				+ "tongue|	혀|\r\n"
				+ "tool|	사용세|\r\n"
				+ "toss|	던지다|\r\n"
				+ "total|	총계 전체의 합계하다|\r\n"
				+ "tough|	단단한|\r\n"
				+ "toward|	-쪽으로|\r\n"
				+ "toxic|	독의|\r\n"
				+ "trace|	발자국|\r\n"
				+ "trade|	매매|\r\n"
				+ "tradition|	전설|\r\n"
				+ "traffic|	교통|\r\n"
				+ "tragic|	비극의|\r\n"
				+ "transfer|	옮기다|\r\n"
				+ "transform|	변형(변용,변태)시키다|\r\n"
				+ "translate|	번역하다|\r\n"
				+ "transport|	수송(운송)하다|\r\n"
				+ "trap|	덫|\r\n"
				+ "tray|	쟁반|\r\n"
				+ "treasure|	보물|\r\n"
				+ "treat|	대우하다|\r\n"
				+ "trend|	방향|\r\n"
				+ "trial|	시험|\r\n"
				+ "tribe|	종족|\r\n"
				+ "trick|	책략|\r\n"
				+ "triumph|	승리|\r\n"
				+ "troop|	대|\r\n"
				+ "trophy|	전리품|\r\n"
				+ "trouble|	고생|\r\n"
				+ "trouser|	즈봉|\r\n"
				+ "trunk|	줄기|\r\n"
				+ "trust|	신용|\r\n"
				+ "truth|	진리|\r\n"
				+ "tube|	관|\r\n"
				+ "tune|	곡|\r\n"
				+ "tunnel|	터널|\r\n"
				+ "tutor|	가정교사|\r\n"
				+ "twin|	쌍동이|\r\n"
				+ "twist|	꼬이다|\r\n"
				+ "typical|	전형적인|\r\n"
				+ "ultimate|	최후의|\r\n"
				+ "uniform|	한결같은|\r\n"
				+ "unify|	하나로 하다|\r\n"
				+ "union|	결합|\r\n"
				+ "unique|	유일무이한|\r\n"
				+ "unit|	단위|\r\n"
				+ "unite|	결합하다|\r\n"
				+ "universe|	우주|\r\n"
				+ "university|	종합대학(교) 대학의(에 관계 있는)|\r\n"
				+ "unless|	-하지 않으면|\r\n"
				+ "until|	-까지|\r\n"
				+ "update|	새롭게 하다 최신정보|\r\n"
				+ "upon|	-의 위에|\r\n"
				+ "upper|	위쪽의|\r\n"
				+ "upset|	뒤집어 엎다|\r\n"
				+ "upward|	위로 향한|\r\n"
				+ "urban|	도시의|\r\n"
				+ "urge|	몰아대다|\r\n"
				+ "urgent|	긴급한|\r\n"
				+ "usual|	평소의|\r\n"
				+ "vacation|	휴가|\r\n"
				+ "vacuum|	진공|\r\n"
				+ "valley|	골짜기|\r\n"
				+ "value|	가치|\r\n"
				+ "van|	유개트럭|\r\n"
				+ "various|	가지가지의|\r\n"
				+ "vary|	바꾸다|\r\n"
				+ "vast|	광대한, 광막한 막대한|\r\n"
				+ "vehicle|	운반 기구, 운송 수단,  수레, 차량, 탈것|\r\n"
				+ "venture|	모험|\r\n"
				+ "version|	번역, 번역문 개작, 각색, 번안|\r\n"
				+ "versus|	…대, …에 대한|\r\n"
				+ "via|	…을 거쳐, …을 경유하여|\r\n"
				+ "victim|	희생, 산 제물, 인신 제물|\r\n"
				+ "victory|	승리, 전승|\r\n"
				+ "view|	봄, 관찰, 개관, 실지 검증  보는 힘, 시계, 시야|\r\n"
				+ "village|	마을, 촌락|\r\n"
				+ "violent|	격렬한, 맹렬한|\r\n"
				+ "visible|	눈에 보이는,  볼 수 있는|\r\n"
				+ "visual|	시각의, 물건을 보기 위한|\r\n"
				+ "vocabulary|	어휘, 용어수, 용어 범위|\r\n"
				+ "volume|	책  권|\r\n"
				+ "voluntary|	자발적인, 수의의|\r\n"
				+ "vote|	찬부 표시, 투표, 표결|\r\n"
				+ "voyage|	여행|\r\n"
				+ "wage|	임금|\r\n"
				+ "warn|	경고하다|\r\n"
				+ "waste|	낭비하다|\r\n"
				+ "wave|	물결|\r\n"
				+ "weak|	약한|\r\n"
				+ "wealth|	재산|\r\n"
				+ "weapon|	무기|\r\n"
				+ "weigh|	무게를 달다|\r\n"
				+ "weird|	불가사의한|\r\n"
				+ "welfare|	행복|\r\n"
				+ "whale|	고래|\r\n"
				+ "wheat|	밀|\r\n"
				+ "wheel|	바퀴|\r\n"
				+ "whether|	-인지 어떤지|\r\n"
				+ "which|	어느 쪽|\r\n"
				+ "while|	동안 -하는 동안|\r\n"
				+ "whisper|	속삭이다|\r\n"
				+ "whistle|	휘파람|\r\n"
				+ "whole|	전체의|\r\n"
				+ "wide|	폭넓은|\r\n"
				+ "widespread|	널리 보급되어 있는|\r\n"
				+ "wild|	야생의|\r\n"
				+ "wing|	날개|\r\n"
				+ "wipe|	닦다|\r\n"
				+ "wire|	철사|\r\n"
				+ "wise|	슬기로운|\r\n"
				+ "wit|	기지|\r\n"
				+ "within|	prop.-의 안쪽에 안으로 내부|\r\n"
				+ "without|	prop.-없이 밖은|\r\n"
				+ "witness|	증언|\r\n"
				+ "wonder|	경이|\r\n"
				+ "wool|	양모|\r\n"
				+ "worship|	숭배|\r\n"
				+ "worth|	가치가 있는 가치|\r\n"
				+ "would|	auwill의 과거|\r\n"
				+ "wound|	부상|\r\n"
				+ "wrap|	싸다|\r\n"
				+ "yell|	고함치다|\r\n"
				+ "yet|	아직|\r\n"
				+ "zone|	구역|\r\n";
		
		String[] legislationArr = legislation.split("\n");
		int chapterIndex = 1;
		StringBuilder chapter = new StringBuilder();
		for(int i=0;i<legislationArr.length;i++) {
			if( (i+1)%40 ==0 ) chapterIndex++;
			String[] word = legislationArr[i].split("\\|");
			chapter.append("chapter");
			chapter.append(chapterIndex);
			VocaDTO voca = VocaDTO.builder()
								  .engWord(word[0].trim())
								  .korWord(word[1].trim())
								  .category(chapter.toString())
								  .build();
			vocaService.create(voca, VOCABOOK_BASIC_ID);
			chapter.setLength(0);
		}
	}
	
	
}
