package com.wordwave.voca;

import java.beans.JavaBean;

@JavaBean
public class VocaDataCode {
	static String basicVoca() {
		String basic = "abandon|	버리다|\r\n"
				+ "able|	할 수 있는|\r\n"
				+ "aboard|	배로|\r\n"
				+ "abroad|	외국으로|\r\n"
				+ "absent|	부재의|\r\n"
				+ "absolute|	절대의|\r\n"
				+ "absorb|	흡수하다|\r\n"
				+ "abstract|	추상적인|\r\n"
				+ "abundant|	풍부한|\r\n"
				+ "abuse|	남용|\r\n"
				+ "accelerate|	가속하다 속도가 가해지다|\r\n"
				+ "accept|	받아들이다|\r\n"
				+ "access|	접근|\r\n"
				+ "accommodate|	수용하다|\r\n"
				+ "accompany|	동반하다|\r\n"
				+ "accomplish|	이루다|\r\n"
				+ "account|	설명하다 계산|\r\n"
				+ "accurate|	정확한|\r\n"
				+ "accuse|	고발하다|\r\n"
				+ "achieve|	성취하다|\r\n"
				+ "acid|	산 신|\r\n"
				+ "acknowledge|	인정하다|\r\n"
				+ "acquire|	얻다|\r\n"
				+ "activate|	활동적으로 하다|\r\n"
				+ "actual|	현실의|\r\n"
				+ "acute|	날카로운|\r\n"
				+ "adapt|	적용시키다|\r\n"
				+ "addict|	열중하게 하다|\r\n"
				+ "adequate|	충분한|\r\n"
				+ "adjust|	맞추다|\r\n"
				+ "administer|	관리하다|\r\n"
				+ "admire|	감복하다|\r\n"
				+ "admission|	입장|\r\n"
				+ "admit|	받아들이다|\r\n"
				+ "adolescent|	청년기의|\r\n"
				+ "adopt|	채용하다|\r\n"
				+ "advance|	나아가다|\r\n"
				+ "advantage|	유리한 입장|\r\n"
				+ "advertize|	광고하다|\r\n"
				+ "advocate|	변호사|\r\n"
				+ "affair|	일|\r\n"
				+ "affect|	영향을 주다|\r\n"
				+ "affection|	애정|\r\n"
				+ "afford|	여유가 있다|\r\n"
				+ "agency|	기능|\r\n"
				+ "agenda|	안건|\r\n"
				+ "agent|	대리인|\r\n"
				+ "aggressive|	침략적인|\r\n"
				+ "agriculture|	농업|\r\n"
				+ "aid|	도와 주다|\r\n"
				+ "aim|	겨누다|\r\n"
				+ "aircraft|	항공기|\r\n"
				+ "aisle|	측면복도|\r\n"
				+ "alert|	빈틈없는|\r\n"
				+ "alien|	외국의|\r\n"
				+ "alike|	비슷한|\r\n"
				+ "alive|	살아있는|\r\n"
				+ "allow|	허락하다|\r\n"
				+ "ally|	동맹하다|\r\n"
				+ "alongside|	-의 곁에|\r\n"
				+ "alter|	바꾸다|\r\n"
				+ "alternative|	어느 한쪽의 양자택일|\r\n"
				+ "although|	비록 -일지라도|\r\n"
				+ "altogether|	전혀|\r\n"
				+ "amaze|	깜짝 놀라게 하다|\r\n"
				+ "ambassador|	대사|\r\n"
				+ "ambition|	야심|\r\n"
				+ "among|	-중에|\r\n"
				+ "amount|	(금액이)-이 되다|\r\n"
				+ "amuse|	재미나게 하다|\r\n"
				+ "analyze|	분해하다|\r\n"
				+ "anchor|	닻|\r\n"
				+ "ancient|	옛날의|\r\n"
				+ "angle|	각|\r\n"
				+ "anniversary|	기념일 예년의|\r\n"
				+ "announce|	알리다|\r\n"
				+ "annoy|	귀찮게하다|\r\n"
				+ "annual|	일년의|\r\n"
				+ "anticipate|	예기하다|\r\n"
				+ "anxiety|	근심|\r\n"
				+ "anxious|	걱정되는|\r\n"
				+ "apart|	떨어져서|\r\n"
				+ "apology|	사과|\r\n"
				+ "apparent|	명백한|\r\n"
				+ "appeal|	간청하다|\r\n"
				+ "appear|	나타나다|\r\n"
				+ "applicant|	지원자|\r\n"
				+ "apply|	(물건을)대다|\r\n"
				+ "appoint|	지정하다|\r\n"
				+ "appreciate|	감상하다|\r\n"
				+ "approach|	다가가다|\r\n"
				+ "appropriate|	적당한|\r\n"
				+ "approve|	시인하다|\r\n"
				+ "approximate|	어림셈의|\r\n"
				+ "architect|	건축가|\r\n"
				+ "architecture|	건축|\r\n"
				+ "argue|	논하다|\r\n"
				+ "arise|	생기다|\r\n"
				+ "army|	육군|\r\n"
				+ "arrange|	가지런히 하다|\r\n"
				+ "arrest|	체포하다|\r\n"
				+ "arrow|	화살|\r\n"
				+ "article|	물품|\r\n"
				+ "artificial|	인공의|\r\n"
				+ "ash|	회|\r\n"
				+ "aside|	곁에|\r\n"
				+ "asleep|	잠들은|\r\n"
				+ "aspect|	관점|\r\n"
				+ "aspire|	열망하다|\r\n"
				+ "assemble|	모으다|\r\n"
				+ "assert|	단언하다|\r\n"
				+ "assess|	(세금 등을)사정하다|\r\n"
				+ "asset|	자산|\r\n"
				+ "assign|	할당하다|\r\n"
				+ "assist|	돕다|\r\n"
				+ "associate|	연상하다|\r\n"
				+ "assume|	취하다|\r\n"
				+ "assure|	보증하다|\r\n"
				+ "astonish|	놀라게 하다|\r\n"
				+ "athlete|	운동가|\r\n"
				+ "atmosphere|	대기|\r\n"
				+ "atom|	원자|\r\n"
				+ "attach|	붙이다|\r\n"
				+ "attack|	공격하다|\r\n"
				+ "attain|	이르다|\r\n"
				+ "attempt|	시도하다|\r\n"
				+ "attend|	출석하다|\r\n"
				+ "attention|	주의|\r\n"
				+ "attitude|	태도|\r\n"
				+ "attract|	끌어 당기다|\r\n"
				+ "attribute|	속성|\r\n"
				+ "auction|	경매|\r\n"
				+ "audience|	청중|\r\n"
				+ "author|	저자|\r\n"
				+ "autobiography|	자서전|\r\n"
				+ "automatic|	자동의|\r\n"
				+ "automobile|	자동차 자동차의|\r\n"
				+ "available|	쓸모있는|\r\n"
				+ "avenue|	가로수길|\r\n"
				+ "average|	평균|\r\n"
				+ "avoid|	피하다|\r\n"
				+ "await|	기다리다|\r\n"
				+ "awake|	깨우다|\r\n"
				+ "award|	상|\r\n"
				+ "aware|	알고 있는|\r\n"
				+ "awesome|	무서운|\r\n"
				+ "awful|	두려운|\r\n"
				+ "awkward|	어색한|\r\n"
				+ "balance|	균형|\r\n"
				+ "ban|	금지|\r\n"
				+ "bang|	강타|\r\n"
				+ "bar|	막대기|\r\n"
				+ "bare|	벌거벗은|\r\n"
				+ "bargain|	매매|\r\n"
				+ "bark|	짖다|\r\n"
				+ "barn|	헛간|\r\n"
				+ "barrier|	장벽|\r\n"
				+ "basis|	기초|\r\n"
				+ "bay|	만|\r\n"
				+ "beam|	광선|\r\n"
				+ "beard|	턱수염|\r\n"
				+ "beast|	짐승|\r\n"
				+ "beat|	치다|\r\n"
				+ "beer|	맥주|\r\n"
				+ "beg|	청하다|\r\n"
				+ "behalf|	위함|\r\n"
				+ "behave|	행동하다|\r\n"
				+ "behavior|	행동|\r\n"
				+ "belong|	속하다|\r\n"
				+ "bend|	구부리다|\r\n"
				+ "beneath|	-의 바로 아래에|\r\n"
				+ "benefit|	이익|\r\n"
				+ "berry|	액과|\r\n"
				+ "bet|	걸다|\r\n"
				+ "betray|	배반하다|\r\n"
				+ "beyond|	저편에|\r\n"
				+ "bias|	치우침|\r\n"
				+ "bible|	성서, 성경|\r\n"
				+ "billion|	10억|\r\n"
				+ "bin|	궤|\r\n"
				+ "bind|	매다|\r\n"
				+ "biography|	전기|\r\n"
				+ "biology|	생물학|\r\n"
				+ "bit|	bite의 과거(분사) 작은 조각|\r\n"
				+ "bitter|	쓴|\r\n"
				+ "blame|	책망하다|\r\n"
				+ "blank|	공백|\r\n"
				+ "blanket|	담요|\r\n"
				+ "blend|	혼합하다|\r\n"
				+ "bless|	축복하다|\r\n"
				+ "blind|	눈먼|\r\n"
				+ "blink|	(눈을)깜빡거리다|\r\n"
				+ "blonde|	(살결이 흰)금발의 여성|\r\n"
				+ "bloom|	쇳덩이|\r\n"
				+ "blossom|	(과수의)꽃|\r\n"
				+ "blow|	강타|\r\n"
				+ "boil|	끓다|\r\n"
				+ "bold|	대담한|\r\n"
				+ "bond|	결속|\r\n"
				+ "boom|	굉음|\r\n"
				+ "boost|	뒤를 밀기|\r\n"
				+ "border|	가장자리|\r\n"
				+ "bore|	고조|\r\n"
				+ "bother|	괴롭히다 근심하다 귀찮음|\r\n"
				+ "bounce|	뛰어오르다|\r\n"
				+ "boundary|	경계|\r\n"
				+ "bow|	절|\r\n"
				+ "breast|	가슴|\r\n"
				+ "breathe|	숨쉬다|\r\n"
				+ "breeze|	미풍|\r\n"
				+ "brick|	벽돌|\r\n"
				+ "bride|	신부|\r\n"
				+ "brief|	단시간의|\r\n"
				+ "brilliant|	빛나는|\r\n"
				+ "broad|	(폭이)넓은|\r\n"
				+ "broadcast|	방송하다|\r\n"
				+ "budget|	예산|\r\n"
				+ "bull|	황소|\r\n"
				+ "bullet|	탄환|\r\n"
				+ "bully|	약한 자를 못살게 구는 자|\r\n"
				+ "bump|	충돌 부딪치다|\r\n"
				+ "bunch|	송이|\r\n"
				+ "bundle|	다발|\r\n"
				+ "burden|	후렴|\r\n"
				+ "burst|	파열하다|\r\n"
				+ "bury|	묻다|\r\n"
				+ "bush|	덤불|\r\n"
				+ "butcher|	정육점주인|\r\n"
				+ "buzz|	윙윙거리는 소리|\r\n"
				+ "cab|	택시|\r\n"
				+ "cabin|	선실|\r\n"
				+ "cable|	해저전신|\r\n"
				+ "calculate|	계산하다|\r\n"
				+ "cancel|	취소하다|\r\n"
				+ "cancer|	암|\r\n"
				+ "candidate|	지원자|\r\n"
				+ "canvas|	돛베|\r\n"
				+ "capable|	할 수 있는|\r\n"
				+ "cape|	곶|\r\n"
				+ "capital|	수위의|\r\n"
				+ "capture|	붙잡다(=catch)|\r\n"
				+ "career|	경력|\r\n"
				+ "carve|	조각하다|\r\n"
				+ "cast|	던지다|\r\n"
				+ "casual|	우연한|\r\n"
				+ "category|	범주|\r\n"
				+ "cattle|	소|\r\n"
				+ "causal|	원인의|\r\n"
				+ "cause|	원인|\r\n"
				+ "caution|	조심|\r\n"
				+ "cave|	동굴 굴을 파다 꺼지다|\r\n"
				+ "cease|	그만두다 그치다 중지|\r\n"
				+ "ceiling|	천장|\r\n"
				+ "celebrate|	경축하다|\r\n"
				+ "celebrity|	명성|\r\n"
				+ "cell|	작은 방|\r\n"
				+ "censor|	검열관|\r\n"
				+ "century|	1세기|\r\n"
				+ "certificate|	증명서|\r\n"
				+ "chairman|	의장|\r\n"
				+ "challenge|	도전|\r\n"
				+ "chaos|	혼돈|\r\n"
				+ "character|	인격|\r\n"
				+ "characteristic|	특유한|\r\n"
				+ "charge|	요금|\r\n"
				+ "charity|	자비|\r\n"
				+ "charm|	매력|\r\n"
				+ "chase|	쫓다|\r\n"
				+ "chat|	잡담|\r\n"
				+ "cheek|	볼|\r\n"
				+ "cheer|	갈채|\r\n"
				+ "chef|	쿡|\r\n"
				+ "chemical|	화학의|\r\n"
				+ "chemistry|	화학|\r\n"
				+ "chest|	가슴팍|\r\n"
				+ "chew|	씹다|\r\n"
				+ "chief|	우두머리|\r\n"
				+ "chill|	차가움|\r\n"
				+ "chin|	턱(끝) 턱에 대다|\r\n"
				+ "chip|	(나무)토막|\r\n"
				+ "choir|	(교회의)성가대|\r\n"
				+ "chop|	(도끼 등으로)자르다|\r\n"
				+ "chorus|	합창|\r\n"
				+ "cigarette|	궐련|\r\n"
				+ "circulate|	순환하다|\r\n"
				+ "circumstance|	환경|\r\n"
				+ "cite|	인용하다(quote)|\r\n"
				+ "citizen|	시민|\r\n"
				+ "civil|	시민의|\r\n"
				+ "claim|	요구하다|\r\n"
				+ "clap|	짝짝|\r\n"
				+ "clarify|	맑게 하다|\r\n"
				+ "clash|	충돌하다|\r\n"
				+ "classic|	고전의|\r\n"
				+ "classify|	분류하다|\r\n"
				+ "clause|	조항|\r\n"
				+ "clay|	찰흙|\r\n"
				+ "client|	소송의뢰인|\r\n"
				+ "cliff|	절벽|\r\n"
				+ "climate|	기후|\r\n"
				+ "cling|	밀착하다|\r\n"
				+ "clinic|	병원|\r\n"
				+ "clue|	단서|\r\n"
				+ "cluster|	떼|\r\n"
				+ "coach|	역마차|\r\n"
				+ "coal|	석탄|\r\n"
				+ "coast|	연안|\r\n"
				+ "code|	법전|\r\n"
				+ "coincide|	일치하다|\r\n"
				+ "collaborate|	공동으로 일하다|\r\n"
				+ "collapse|	붕괴|\r\n"
				+ "collar|	칼라|\r\n"
				+ "colleague|	동료|\r\n"
				+ "colony|	식민지|\r\n"
				+ "column|	(신문 등의)난|\r\n"
				+ "combat|	격투하다|\r\n"
				+ "combine|	결합하다|\r\n"
				+ "comfort|	위안|\r\n"
				+ "command|	명령하다|\r\n"
				+ "comment|	논평|\r\n"
				+ "commerce|	상업|\r\n"
				+ "commission|	위임|\r\n"
				+ "commit|	위탁하다|\r\n"
				+ "committee|	위원회|\r\n"
				+ "communicate|	알리다|\r\n"
				+ "communist|	공산주의자|\r\n"
				+ "community|	공동생활체|\r\n"
				+ "companion|	동료|\r\n"
				+ "compare|	비교하다|\r\n"
				+ "compete|	경쟁하다|\r\n"
				+ "competent|	능력있는|\r\n"
				+ "complain|	불평하다|\r\n"
				+ "complement|	보완하는 것|\r\n"
				+ "complete|	완성하다|\r\n"
				+ "complex|	합성물|\r\n"
				+ "complicate|	복잡하게 하다|\r\n"
				+ "compose|	구성하다|\r\n"
				+ "comprehensive|	이해력있는|\r\n"
				+ "conceal|	숨기다|\r\n"
				+ "concentrate|	집중하다|\r\n"
				+ "concept|	개념|\r\n"
				+ "concern|	관계하다|\r\n"
				+ "conclude|	결정하다|\r\n"
				+ "concrete|	구체적인 응고물|\r\n"
				+ "conduct|	행위 이끌다|\r\n"
				+ "confess|	실토하다|\r\n"
				+ "confident|	확신하는|\r\n"
				+ "confine|	국경|\r\n"
				+ "confirm|	확인하다|\r\n"
				+ "conflict|	투쟁|\r\n"
				+ "conform|	일치시키다|\r\n"
				+ "confront|	직면하다|\r\n"
				+ "confuse|	혼란시키다|\r\n"
				+ "congress|	회의|\r\n"
				+ "connect|	잇다 이어지다|\r\n"
				+ "conscience|	양심|\r\n"
				+ "conscious|	의식적인|\r\n"
				+ "consider|	숙고하다|\r\n"
				+ "consist|	-으로 이루어지다|\r\n"
				+ "consistent|	시종일관한|\r\n"
				+ "constant|	불변의|\r\n"
				+ "construct|	건조하다|\r\n"
				+ "consult|	상의하다|\r\n"
				+ "consume|	소비하다|\r\n"
				+ "contact|	접촉|\r\n"
				+ "contain|	내포하다|\r\n"
				+ "content|	만족하여|\r\n"
				+ "context|	문맥|\r\n"
				+ "continent|	자제심이 있는|\r\n"
				+ "continue|	계속하다|\r\n"
				+ "contract|	계약|\r\n"
				+ "contrary|	반대의 반대 거꾸로|\r\n"
				+ "contrast|	대조|\r\n"
				+ "contribute|	기부하다|\r\n"
				+ "controversy|	논쟁|\r\n"
				+ "convenient|	편리한|\r\n"
				+ "conversation|	회화|\r\n"
				+ "convey|	나르다|\r\n"
				+ "convict|	유죄로 판결하다 죄수|\r\n"
				+ "convince|	확신시키다|\r\n"
				+ "cooperate|	협동하다|\r\n"
				+ "cop|	순경|\r\n"
				+ "cope|	코우프(성직자의 긴 겉옷)|\r\n"
				+ "copyright|	판권|\r\n"
				+ "cord|	밧줄|\r\n"
				+ "core|	핵심|\r\n"
				+ "corn|	티눈|\r\n"
				+ "corporate|	법인조직의|\r\n"
				+ "correct|	옳은|\r\n"
				+ "correspond|	일치하다|\r\n"
				+ "corrupt|	타락한|\r\n"
				+ "costume|	복장|\r\n"
				+ "cottage|	시골집|\r\n"
				+ "couch|	침대|\r\n"
				+ "cough|	기침 기침을 하다 기침을 하여 -을 뱉어내다|\r\n"
				+ "council|	회의|\r\n"
				+ "counsel|	의논|\r\n"
				+ "count|	계산|\r\n"
				+ "counter|	계산하는 사람|\r\n"
				+ "courage|	용기|\r\n"
				+ "cowboy|	목동|\r\n"
				+ "crack|	찰싹 소리내다 금가다 날카로운소리|\r\n"
				+ "craft|	솜씨|\r\n"
				+ "crash|	도산|\r\n"
				+ "crawl|	네발로 기다|\r\n"
				+ "create|	창조하다|\r\n"
				+ "creature|	창조물|\r\n"
				+ "credible|	믿을 수 있는|\r\n"
				+ "credit|	신용|\r\n"
				+ "crew|	승무원|\r\n"
				+ "cricket|	크리켓|\r\n"
				+ "crime|	범죄|\r\n"
				+ "criminal|	죄의|\r\n"
				+ "crisis|	위기|\r\n"
				+ "crisp|	파삭파삭한|\r\n"
				+ "critic|	비평가|\r\n"
				+ "criticize|	비평하다|\r\n"
				+ "criticism|	비평|\r\n"
				+ "crop|	수확|\r\n"
				+ "crucial|	결정적인|\r\n"
				+ "cruel|	잔인한|\r\n"
				+ "cruise|	순항하다|\r\n"
				+ "crush|	눌러 부수다|\r\n"
				+ "crystal|	수정|\r\n"
				+ "cultivate|	경작하다|\r\n"
				+ "cupboard|	찬장|\r\n"
				+ "cure|	치료|\r\n"
				+ "curl|	곱슬머리 머리털을 지지다|\r\n"
				+ "current|	유행의|\r\n"
				+ "curry|	카레요리 카레로 맛을 내다|\r\n"
				+ "curve|	곡선|\r\n"
				+ "custom|	습관|\r\n"
				+ "dairy|	낙농장|\r\n"
				+ "dam|	댐|\r\n"
				+ "damage|	손해|\r\n"
				+ "damp|	축축한 습기 적시다|\r\n"
				+ "dare|	au감히 -하다|\r\n"
				+ "darling|	귀여운|\r\n"
				+ "dash|	돌진|\r\n"
				+ "database|	데이터베이스|\r\n"
				+ "dawn|	새벽 날이 새다|\r\n"
				+ "deal|	양|\r\n"
				+ "debate|	토론 토론하다|\r\n"
				+ "debt|	빚|\r\n"
				+ "decade|	10년간|\r\n"
				+ "decay|	쇠퇴하다|\r\n"
				+ "decision|	결정|\r\n"
				+ "deck|	갑판|\r\n"
				+ "declare|	선언하다|\r\n"
				+ "decline|	기울다|\r\n"
				+ "decorate|	장식하다|\r\n"
				+ "decrease|	감소하다|\r\n"
				+ "defeat|	패배|\r\n"
				+ "defense|	방어|\r\n"
				+ "defend|	방어하다|\r\n"
				+ "defendant|	피고 피고의|\r\n"
				+ "define|	정의하다|\r\n"
				+ "definite|	일정한|\r\n"
				+ "degree|	도|\r\n"
				+ "delay|	늦추다|\r\n"
				+ "delete|	삭제하다|\r\n"
				+ "delicate|	미묘한|\r\n"
				+ "delight|	즐겁게하다 즐거워하다|\r\n"
				+ "deliver|	인도하다|\r\n"
				+ "demand|	요구하다|\r\n"
				+ "democracy|	민주주의|\r\n"
				+ "democrat|	민주주의자|\r\n"
				+ "demon|	악마|\r\n"
				+ "demonstrate|	증명하다|\r\n"
				+ "dense|	짙은|\r\n"
				+ "deny|	부정하다|\r\n"
				+ "department|	부|\r\n"
				+ "departure|	출발|\r\n"
				+ "depend|	좌우되다|\r\n"
				+ "dependence|	종속|\r\n"
				+ "depress|	억압하다|\r\n"
				+ "derive|	이끌어 내다|\r\n"
				+ "descend|	내려오다|\r\n"
				+ "describe|	기술하다|\r\n"
				+ "description|	서술|\r\n"
				+ "desert|	버리다|\r\n"
				+ "deserve|	 -할 만하다|\r\n"
				+ "desire|	바라다|\r\n"
				+ "despair|	절망하다|\r\n"
				+ "desperate|	절망적인|\r\n"
				+ "despite|	-에도 불구하고 모욕|\r\n"
				+ "destination|	목적지|\r\n"
				+ "destiny|	운명|\r\n"
				+ "destroy|	파괴하다|\r\n"
				+ "destruction|	파괴|\r\n"
				+ "detach|	분리하다|\r\n"
				+ "detail|	상설|\r\n"
				+ "detect|	간파하다|\r\n"
				+ "determine|	결정하다|\r\n"
				+ "develop|	발달하다|\r\n"
				+ "device|	고안|\r\n"
				+ "devil|	악마|\r\n"
				+ "devise|	고안하다|\r\n"
				+ "devote|	바치다|\r\n"
				+ "dictionary|	사전|\r\n";
		return basic;
	}
}
