name: CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create application.properties
        run: |
          cd ./src/main/resources
          
          # application.properties 파일 생성
          touch application.properties
          
          # GitHub-Actions 에서 설정한 값을 application.properties 파일에 쓰기
          echo "spring.datasource.url=${{ secrets.DB_URL }}" >> application.properties
          echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> application.properties
          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> application.properties
          echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> application.properties
          echo "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect" >> application.properties
          echo "spring.jpa.properties.hibernate.show_sql=true" >> application.properties
          echo "spring.jpa.properties.hibernate.format_sql=true" >> application.properties
          echo "spring.jpa.hibernate.ddl-auto=update" >> application.properties
          # SMTP 설정
          echo "spring.mail.host=smtp.gmail.com" >> application.properties
          echo "spring.mail.port=587" >> application.properties
          echo "spring.mail.username=wordwave492@gmail.com" >> application.properties
          echo "spring.mail.password=${{ secrets.MAIL_PASSWORD }}" >> application.properties
          echo "spring.mail.properties.mail.smtp.starttls.enable=true" >> application.properties
          echo "spring.mail.properties.mail.smtp.auth=true" >> application.properties
          echo "spring.mail.properties.mail.debug=true" >> application.properties
          echo "spring.mail.properties.mail.mime.charset=UTF-8" >> application.properties
          echo "spring.mail.properties.mail.transport.protocol=smtp" >> application.properties
          # Redis 설정
          echo "spring.data.redis.host=${{ secrets.REDIS_HOST }}" >> ./application.properties
          echo "spring.data.redis.port=${{ secrets.REDIS_PORT }}" >> ./application.properties
          # Swagger 설정 추가
          echo "springdoc.api-docs.path=/api-docs" >> application.properties
          echo "springdoc.swagger-ui.path=/swagger-ui.html" >> application.properties
          echo "server.forward-headers-strategy=framework" >> application.properties
          # Thymeleaf 설정
          echo "spring.thymeleaf.prefix=classpath:/templates/" >> application.properties

          # AWS S3 설정
          echo "cloud.aws.region.static=${{ secrets.AWS_REGION }}" >> application.properties
          echo "cloud.aws.stack.auto=false" >> application.properties
          echo "cloud.aws.credentials.accessKey=${{ secrets.AWS_ACCESS_KEY }}" >> application.properties
          echo "cloud.aws.credentials.secretKey=${{ secrets.AWS_SECRET_KEY }}" >> application.properties
          echo "cloud.aws.s3.bucket=${{ secrets.S3_BUCKET_NAME }}" >> application.properties
           # 파일 업로드 설정
          echo "spring.servlet.multipart.max-file-size=2MB" >> application.properties
          echo "spring.servlet.multipart.max-request-size=2MB" >> application.properties
          
          # HikariCP 설정
          echo "spring.datasource.hikari.connection-timeout=30000" >> application.properties
          echo "spring.datasource.hikari.minimum-idle=10" >> application.properties
          echo "spring.datasource.hikari.maximum-pool-size=20" >> application.properties
          echo "spring.datasource.hikari.idle-timeout=600000" >> application.properties
          echo "spring.datasource.hikari.max-lifetime=1800000" >> application.properties

          # SSL KeyStore 설정
          echo "server.port=443" >> application.properties
          echo "server.ssl.key-store=file:/etc/letsencrypt/live/wordwave.xyz/keystore.p12" >> application.properties
          echo "server.ssl.key-store-type=PKCS12" >> application.properties
          echo "server.ssl.key-store-password=${{ secrets.SSL_PASSWORD }}" >> application.properties
          echo "server.ssl.key-alias=wordwave.xyz" >> application.properties
          
        shell: bash

      - name: Build with Gradle
        run: |
          chmod +x gradlew 
          ./gradlew build -x test
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECREAT_KEY }}
          
      ## 웹 이미지 빌드 및 도커허브에 push
      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }} . 
          docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}



      ## docker compose up
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.KEY }}
          script: |
            sudo docker rm -f $(sudo docker ps -aq) # 모든 컨테이너를 강제로 제거
            sudo docker pull ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}
            cd ~
            sudo docker-compose up -d
            sudo docker image prune -f


